// Generowane: tests/widget-i18n.test.ts (UPDATE_WIDGET=1) — nie edytuj ręcznie.
// Etykiety rodzaju odliczania w 16 językach aplikacji (zapas, gdy aplikacja nie przekaże etykiety w polu kind).
let restLabels: [String: (rest: String, set: String)] = [
  "pl": (rest: "Przerwa", set: "Seria"),
  "en": (rest: "Rest", set: "Set"),
  "cs": (rest: "Pauza", set: "Série"),
  "sk": (rest: "Pauza", set: "Séria"),
  "hu": (rest: "Pihenő", set: "Sorozat"),
  "ro": (rest: "Pauză", set: "Serie"),
  "bg": (rest: "Почивка", set: "Серия"),
  "hr": (rest: "Odmor", set: "Serija"),
  "sl": (rest: "Počitek", set: "Serija"),
  "sr": (rest: "Одмор", set: "Серија"),
  "lt": (rest: "Poilsis", set: "Serija"),
  "lv": (rest: "Atpūta", set: "Sērija"),
  "et": (rest: "Paus", set: "Seeria"),
  "uk": (rest: "Відпочинок", set: "Підхід"),
  "es": (rest: "Descanso", set: "Serie"),
  "pt": (rest: "Descanso", set: "Série"),
  "de": (rest: "Pause", set: "Satz"),
  "fr": (rest: "Repos", set: "Série"),
  "it": (rest: "Recupero", set: "Serie"),
  "nl": (rest: "Rust", set: "Set"),
  "sv": (rest: "Vila", set: "Set"),
  "da": (rest: "Pause", set: "Sæt"),
  "nb": (rest: "Pause", set: "Sett"),
  "fi": (rest: "Palautus", set: "Sarja"),
  "tr": (rest: "Dinlenme", set: "Set"),
  "el": (rest: "Διάλειμμα", set: "Σετ"),
]
