// Generowane: tests/widget-i18n.test.ts (UPDATE_WIDGET=1) — nie edytuj ręcznie.
// Etykiety rodzaju odliczania w 16 językach aplikacji (zapas, gdy aplikacja nie przekaże etykiety w polu kind).
let restLabels: [String: (rest: String, set: String, skip: String, shorter: String, longer: String)] = [
  "pl": (rest: "Przerwa", set: "Seria", skip: "Pomiń", shorter: "Skróć przerwę o 15 sekund", longer: "Wydłuż przerwę o 15 sekund"),
  "en": (rest: "Rest", set: "Set", skip: "Skip", shorter: "Shorten rest by 15 seconds", longer: "Extend rest by 15 seconds"),
  "cs": (rest: "Pauza", set: "Série", skip: "Přeskočit", shorter: "Zkrátit pauzu o 15 sekund", longer: "Prodloužit pauzu o 15 sekund"),
  "sk": (rest: "Pauza", set: "Séria", skip: "Preskočiť", shorter: "Skrátiť pauzu o 15 sekúnd", longer: "Predĺžiť pauzu o 15 sekúnd"),
  "hu": (rest: "Pihenő", set: "Sorozat", skip: "Kihagyás", shorter: "Pihenő rövidítése 15 másodperccel", longer: "Pihenő meghosszabbítása 15 másodperccel"),
  "ro": (rest: "Pauză", set: "Serie", skip: "Omite", shorter: "Scurtează pauza cu 15 secunde", longer: "Prelungește pauza cu 15 secunde"),
  "bg": (rest: "Почивка", set: "Серия", skip: "Пропускане", shorter: "Скъсяване на почивката с 15 секунди", longer: "Удължаване на почивката с 15 секунди"),
  "hr": (rest: "Odmor", set: "Serija", skip: "Preskoči", shorter: "Skrati odmor za 15 sekundi", longer: "Produlji odmor za 15 sekundi"),
  "sl": (rest: "Počitek", set: "Serija", skip: "Preskoči", shorter: "Skrajšaj počitek za 15 sekund", longer: "Podaljšaj počitek za 15 sekund"),
  "sr": (rest: "Одмор", set: "Серија", skip: "Прескочи", shorter: "Скрати одмор за 15 секунди", longer: "Продужи одмор за 15 секунди"),
  "lt": (rest: "Poilsis", set: "Serija", skip: "Praleisti", shorter: "Sutrumpinti poilsį 15 sekundžių", longer: "Pailginti poilsį 15 sekundžių"),
  "lv": (rest: "Atpūta", set: "Sērija", skip: "Izlaist", shorter: "Saīsināt atpūtu par 15 sekundēm", longer: "Pagarināt atpūtu par 15 sekundēm"),
  "et": (rest: "Paus", set: "Seeria", skip: "Jäta vahele", shorter: "Lühenda pausi 15 sekundi võrra", longer: "Pikenda pausi 15 sekundi võrra"),
  "uk": (rest: "Відпочинок", set: "Підхід", skip: "Пропустити", shorter: "Скоротити відпочинок на 15 секунд", longer: "Подовжити відпочинок на 15 секунд"),
  "es": (rest: "Descanso", set: "Serie", skip: "Omitir", shorter: "Acortar el descanso 15 segundos", longer: "Alargar el descanso 15 segundos"),
  "pt": (rest: "Descanso", set: "Série", skip: "Ignorar", shorter: "Encurtar descanso em 15 segundos", longer: "Prolongar descanso em 15 segundos"),
  "de": (rest: "Pause", set: "Satz", skip: "Überspringen", shorter: "Pause um 15 Sekunden verkürzen", longer: "Pause um 15 Sekunden verlängern"),
  "fr": (rest: "Repos", set: "Série", skip: "Passer", shorter: "Raccourcir le repos de 15 secondes", longer: "Allonger le repos de 15 secondes"),
  "it": (rest: "Recupero", set: "Serie", skip: "Salta", shorter: "Accorcia il recupero di 15 secondi", longer: "Allunga il recupero di 15 secondi"),
  "nl": (rest: "Rust", set: "Set", skip: "Sla over", shorter: "Verkort rust met 15 seconden", longer: "Verleng rust met 15 seconden"),
  "sv": (rest: "Vila", set: "Set", skip: "Hoppa över", shorter: "Korta vilan med 15 sekunder", longer: "Förläng vilan med 15 sekunder"),
  "da": (rest: "Pause", set: "Sæt", skip: "Spring over", shorter: "Forkort pausen med 15 sekunder", longer: "Forlæng pausen med 15 sekunder"),
  "nb": (rest: "Pause", set: "Sett", skip: "Hopp over", shorter: "Forkort pausen med 15 sekunder", longer: "Forleng pausen med 15 sekunder"),
  "fi": (rest: "Palautus", set: "Sarja", skip: "Ohita", shorter: "Lyhennä palautusta 15 sekuntia", longer: "Pidennä palautusta 15 sekuntia"),
  "tr": (rest: "Dinlenme", set: "Set", skip: "Atla", shorter: "Dinlenmeyi 15 saniye kısalt", longer: "Dinlenmeyi 15 saniye uzat"),
  "el": (rest: "Διάλειμμα", set: "Σετ", skip: "Παράλειψη", shorter: "Μείωση διαλείμματος κατά 15 δευτερόλεπτα", longer: "Παράταση διαλείμματος κατά 15 δευτερόλεπτα"),
]
// Widżet na ekran główny (SummaryWidget.swift, 07.10.2026 wieczór): nazwa i opis w galerii, tekst bez danych.
let summaryWidgetLabels: [String: (title: String, description: String, none: String)] = [
  "pl": (title: "Tydzień treningów", description: "Treningi i serie w tym tygodniu oraz ostatni trening.", none: "Jeszcze bez treningu"),
  "en": (title: "Training week", description: "Workouts and sets this week, plus your last workout.", none: "No workout yet"),
  "cs": (title: "Tréninkový týden", description: "Tréninky a série tento týden a poslední trénink.", none: "Zatím bez tréninku"),
  "sk": (title: "Tréningový týždeň", description: "Tréningy a série tento týždeň a posledný tréning.", none: "Zatiaľ bez tréningu"),
  "hu": (title: "Edzéshét", description: "A heti edzések és sorozatok, valamint a legutóbbi edzés.", none: "Még nincs edzés"),
  "ro": (title: "Săptămâna de antrenament", description: "Antrenamentele și seriile din această săptămână și ultimul antrenament.", none: "Încă niciun antrenament"),
  "bg": (title: "Тренировъчна седмица", description: "Тренировки и серии тази седмица и последната тренировка.", none: "Още няма тренировка"),
  "hr": (title: "Tjedan treninga", description: "Treninzi i serije ovaj tjedan te zadnji trening.", none: "Još nema treninga"),
  "sl": (title: "Teden treningov", description: "Treningi in serije ta teden ter zadnji trening.", none: "Še brez treninga"),
  "sr": (title: "Недеља тренинга", description: "Тренинзи и серије ове недеље и последњи тренинг.", none: "Још нема тренинга"),
  "lt": (title: "Treniruočių savaitė", description: "Šios savaitės treniruotės ir serijos bei paskutinė treniruotė.", none: "Dar nėra treniruočių"),
  "lv": (title: "Treniņu nedēļa", description: "Šīs nedēļas treniņi un sērijas, kā arī pēdējais treniņš.", none: "Vēl nav treniņu"),
  "et": (title: "Treeningnädal", description: "Selle nädala treeningud ja seeriad ning viimane treening.", none: "Treeninguid veel pole"),
  "uk": (title: "Тиждень тренувань", description: "Тренування й підходи цього тижня та останнє тренування.", none: "Ще немає тренувань"),
  "es": (title: "Semana de entreno", description: "Entrenos y series de esta semana y tu último entreno.", none: "Aún sin entrenos"),
  "pt": (title: "Semana de treino", description: "Treinos e séries desta semana e o último treino.", none: "Ainda sem treinos"),
  "de": (title: "Trainingswoche", description: "Einheiten und Sätze dieser Woche sowie dein letztes Training.", none: "Noch kein Training"),
  "fr": (title: "Semaine d’entraînement", description: "Séances et séries de la semaine, et votre dernière séance.", none: "Aucune séance pour l’instant"),
  "it": (title: "Settimana di allenamento", description: "Allenamenti e serie di questa settimana e l’ultimo allenamento.", none: "Ancora nessun allenamento"),
  "nl": (title: "Trainingsweek", description: "Trainingen en sets van deze week en je laatste training.", none: "Nog geen training"),
  "sv": (title: "Träningsvecka", description: "Pass och set den här veckan samt ditt senaste pass.", none: "Inga pass än"),
  "da": (title: "Træningsuge", description: "Træninger og sæt i denne uge samt din seneste træning.", none: "Ingen træning endnu"),
  "nb": (title: "Treningsuke", description: "Økter og sett denne uken, og din siste økt.", none: "Ingen økter ennå"),
  "fi": (title: "Treeniviikko", description: "Tämän viikon treenit ja sarjat sekä viimeisin treeni.", none: "Ei vielä treenejä"),
  "tr": (title: "Antrenman haftası", description: "Bu haftaki antrenmanlar ve setler ile son antrenmanın.", none: "Henüz antrenman yok"),
  "el": (title: "Εβδομάδα προπονήσεων", description: "Προπονήσεις και σετ αυτή την εβδομάδα και η τελευταία προπόνηση.", none: "Καμία προπόνηση ακόμη"),
]
