// Generowane: tests/widget-i18n.test.ts (UPDATE_WIDGET=1) — nie edytuj ręcznie.
// Etykiety rodzaju odliczania w 16 językach aplikacji (zapas, gdy aplikacja nie przekaże etykiety w polu kind).
let restLabels: [String: (rest: String, set: String, skip: String, shorter: String, longer: String)] = [
  "pl": (rest: "Przerwa", set: "Seria", skip: "Pomiń", shorter: "Skróć przerwę o 15 sekund", longer: "Wydłuż przerwę o 15 sekund"),
  "en": (rest: "Rest", set: "Set", skip: "Skip", shorter: "Shorten rest by 15 seconds", longer: "Extend rest by 15 seconds"),
  "cs": (rest: "Pauza", set: "Série", skip: "Přeskočit", shorter: "Zkrátit pauzu o 15 sekund", longer: "Prodloužit pauzu o 15 sekund"),
  "sk": (rest: "Pauza", set: "Séria", skip: "Preskočiť", shorter: "Skrátiť pauzu o 15 sekúnd", longer: "Predĺžiť pauzu o 15 sekúnd"),
  "hu": (rest: "Pihenő", set: "Sorozat", skip: "Kihagyás", shorter: "Pihenő rövidítése 15 másodperccel", longer: "Pihenő meghosszabbítása 15 másodperccel"),
  "ro": (rest: "Pauză", set: "Serie", skip: "Omite", shorter: "Scurtează pauza cu 15 secunde", longer: "Prelungește pauza cu 15 secunde"),
  "bg": (rest: "Почивка", set: "Серия", skip: "Пропускане", shorter: "Скъсяване на почивката с 15 секунди", longer: "Удължаване на почивката с 15 секунди"),
  "hr": (rest: "Odmor", set: "Serija", skip: "Preskoči", shorter: "Skrati odmor za 15 sekundi", longer: "Produlji odmor za 15 sekundi"),
  "sl": (rest: "Počitek", set: "Serija", skip: "Preskoči", shorter: "Skrajšaj počitek za 15 sekund", longer: "Podaljšaj počitek za 15 sekund"),
  "sr": (rest: "Одмор", set: "Серија", skip: "Прескочи", shorter: "Скрати одмор за 15 секунди", longer: "Продужи одмор за 15 секунди"),
  "lt": (rest: "Poilsis", set: "Serija", skip: "Praleisti", shorter: "Sutrumpinti poilsį 15 sekundžių", longer: "Pailginti poilsį 15 sekundžių"),
  "lv": (rest: "Atpūta", set: "Sērija", skip: "Izlaist", shorter: "Saīsināt atpūtu par 15 sekundēm", longer: "Pagarināt atpūtu par 15 sekundēm"),
  "et": (rest: "Paus", set: "Seeria", skip: "Jäta vahele", shorter: "Lühenda pausi 15 sekundi võrra", longer: "Pikenda pausi 15 sekundi võrra"),
  "uk": (rest: "Відпочинок", set: "Підхід", skip: "Пропустити", shorter: "Скоротити відпочинок на 15 секунд", longer: "Подовжити відпочинок на 15 секунд"),
  "es": (rest: "Descanso", set: "Serie", skip: "Omitir", shorter: "Acortar el descanso 15 segundos", longer: "Alargar el descanso 15 segundos"),
  "pt": (rest: "Descanso", set: "Série", skip: "Ignorar", shorter: "Encurtar descanso em 15 segundos", longer: "Prolongar descanso em 15 segundos"),
  "de": (rest: "Pause", set: "Satz", skip: "Überspringen", shorter: "Pause um 15 Sekunden verkürzen", longer: "Pause um 15 Sekunden verlängern"),
  "fr": (rest: "Repos", set: "Série", skip: "Passer", shorter: "Raccourcir le repos de 15 secondes", longer: "Allonger le repos de 15 secondes"),
  "it": (rest: "Recupero", set: "Serie", skip: "Salta", shorter: "Accorcia il recupero di 15 secondi", longer: "Allunga il recupero di 15 secondi"),
  "nl": (rest: "Rust", set: "Set", skip: "Sla over", shorter: "Verkort rust met 15 seconden", longer: "Verleng rust met 15 seconden"),
  "sv": (rest: "Vila", set: "Set", skip: "Hoppa över", shorter: "Korta vilan med 15 sekunder", longer: "Förläng vilan med 15 sekunder"),
  "da": (rest: "Pause", set: "Sæt", skip: "Spring over", shorter: "Forkort pausen med 15 sekunder", longer: "Forlæng pausen med 15 sekunder"),
  "nb": (rest: "Pause", set: "Sett", skip: "Hopp over", shorter: "Forkort pausen med 15 sekunder", longer: "Forleng pausen med 15 sekunder"),
  "fi": (rest: "Palautus", set: "Sarja", skip: "Ohita", shorter: "Lyhennä palautusta 15 sekuntia", longer: "Pidennä palautusta 15 sekuntia"),
  "tr": (rest: "Dinlenme", set: "Set", skip: "Atla", shorter: "Dinlenmeyi 15 saniye kısalt", longer: "Dinlenmeyi 15 saniye uzat"),
  "el": (rest: "Διάλειμμα", set: "Σετ", skip: "Παράλειψη", shorter: "Μείωση διαλείμματος κατά 15 δευτερόλεπτα", longer: "Παράταση διαλείμματος κατά 15 δευτερόλεπτα"),
]
