/* AUTOMATYCZNIE WYGENEROWANE przez scripts/equipment/gen.mjs z docs/research/equipment/catalog.json — nie edytować ręcznie.
 * Wymagania sprzętowe ćwiczeń biblioteki (P-003): requires = każda grupa musi być spełniona, w grupie wystarczy jedna możliwość. */
export type LoadSource = 'barbell' | 'dumbbell' | 'cable' | 'machine_stack' | 'bodyweight' | 'trap_bar' | 'ez_bar' | 'plate_loaded_machine' | 'kettlebell' | 'smith' | 'band' | 'none';
export type Pattern = 'h_push' | 'h_pull' | 'v_push' | 'v_pull' | 'squat' | 'hinge' | 'lunge_single_leg' | 'isolation' | 'core_flexion' | 'core_anti_ext' | 'core_anti_rot' | 'core_other' | 'carry' | 'cardio' | 'other';
export interface CatalogEntry { requires: string[][]; recommended: string[]; loadSource: LoadSource; pattern: Pattern; implements?: 1 | 2 }
/** Wersja treści katalogu (skrót) — zapisywana w ćwiczeniu jako catalogRev. */
export const CATALOG_REV = '9af5cce62cac';
/** Słownik możliwości użytych w katalogu (wymagane i zalecane), posortowany. */
export const CATALOG_CAPS: readonly string[] = ["ab_crunch_machine","ab_wheel","ankle_strap","bands","barbell","battle_ropes","belt_squat_machine","bench.decline","bench.flat","bench.incline","bench.uprights","biceps_curl_machine","box","cable.dual","cable.high","cable.low","cable.mid","cable.rope","cable.row_seat","calf_machine","cardio.bike","cardio.elliptical","cardio.rower","cardio.ski","cardio.stair","cardio.treadmill","chest_press_machine","db","dip.bars","dip_belt","ez_bar","floor_mat","ghd","glute_ham_raise","glute_kickback_machine","hack_squat","hip_abductor_adductor","hip_thrust_machine","hyperext_bench","jump_rope","kb","landmine","lat_pulldown","lateral_raise_machine","leg_curl","leg_ext","leg_press","med_ball","outdoor","pec_deck","pendulum_squat","preacher_bench","pullover_machine","pullup.bar","rack","rack.safeties","reverse_hyper","rings","row_machine","shoulder_press_machine","sled","sliders","smith","stability_ball","suspension","t_bar","trap_bar","triceps_ext_machine"];
export const CATALOG: Readonly<Record<string, CatalogEntry>> = {
  "Bench Press (sztanga)": {"requires":[["barbell"],["bench.flat"],["rack","bench.uprights"]],"recommended":["rack.safeties"],"loadSource":"barbell","pattern":"h_push"},
  "Bench Press (hantle)": {"requires":[["db"],["bench.flat"]],"recommended":[],"loadSource":"dumbbell","pattern":"h_push","implements":2},
  "Incline Bench Press (sztanga)": {"requires":[["barbell"],["bench.incline"],["rack","bench.uprights"]],"recommended":["rack.safeties"],"loadSource":"barbell","pattern":"h_push"},
  "Incline Bench Press (hantle)": {"requires":[["db"],["bench.incline"]],"recommended":[],"loadSource":"dumbbell","pattern":"h_push","implements":2},
  "Decline Bench Press": {"requires":[["barbell"],["bench.decline"],["rack","bench.uprights"]],"recommended":["rack.safeties"],"loadSource":"barbell","pattern":"h_push"},
  "Chest Fly (hantle)": {"requires":[["db"],["bench.flat"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Cable Fly": {"requires":[["cable.dual"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Pec Deck": {"requires":[["pec_deck"]],"recommended":[],"loadSource":"machine_stack","pattern":"isolation"},
  "Machine Chest Press": {"requires":[["chest_press_machine"]],"recommended":[],"loadSource":"machine_stack","pattern":"h_push"},
  "Wyciskanie na linkach (stojąc)": {"requires":[["cable.dual"],["cable.mid"]],"recommended":[],"loadSource":"cable","pattern":"h_push"},
  "Chest Dip": {"requires":[["dip.bars","rings"]],"recommended":[],"loadSource":"bodyweight","pattern":"v_push"},
  "Push Up": {"requires":[],"recommended":[],"loadSource":"bodyweight","pattern":"h_push"},
  "Incline Push Up": {"requires":[["bench.flat","box"]],"recommended":[],"loadSource":"bodyweight","pattern":"h_push"},
  "Diamond Push Up": {"requires":[],"recommended":[],"loadSource":"bodyweight","pattern":"h_push"},
  "Deadlift (sztanga)": {"requires":[["barbell"]],"recommended":[],"loadSource":"barbell","pattern":"hinge"},
  "Deadlift (hantle)": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"hinge","implements":2},
  "Sumo Deadlift": {"requires":[["barbell"]],"recommended":[],"loadSource":"barbell","pattern":"hinge"},
  "Trap Bar Deadlift": {"requires":[["trap_bar"]],"recommended":[],"loadSource":"trap_bar","pattern":"hinge"},
  "RDL (sztanga)": {"requires":[["barbell"]],"recommended":["rack"],"loadSource":"barbell","pattern":"hinge"},
  "RDL (hantle/linki)": {"requires":[["db","cable.low"]],"recommended":[],"loadSource":"dumbbell","pattern":"hinge","implements":2},
  "Bent Over Row (sztanga)": {"requires":[["barbell"]],"recommended":["rack"],"loadSource":"barbell","pattern":"h_pull"},
  "Bent Over Row (hantle)": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"h_pull","implements":2},
  "Pendlay Row": {"requires":[["barbell"]],"recommended":[],"loadSource":"barbell","pattern":"h_pull"},
  "One Arm Row (hantle)": {"requires":[["db"]],"recommended":["bench.flat"],"loadSource":"dumbbell","pattern":"h_pull","implements":1},
  "Chest Supported Row": {"requires":[["db"],["bench.incline"]],"recommended":[],"loadSource":"dumbbell","pattern":"h_pull","implements":2},
  "T-Bar Row": {"requires":[["t_bar","landmine"],["t_bar","barbell"]],"recommended":[],"loadSource":"barbell","pattern":"h_pull"},
  "Seated Cable Row": {"requires":[["cable.row_seat","cable.low"]],"recommended":[],"loadSource":"cable","pattern":"h_pull"},
  "Wiosłowanie na linkach (siedząc)": {"requires":[["cable.row_seat","cable.low"]],"recommended":[],"loadSource":"cable","pattern":"h_pull"},
  "Lat Pulldown": {"requires":[["lat_pulldown","cable.high"]],"recommended":[],"loadSource":"cable","pattern":"v_pull"},
  "Straight Arm Pulldown": {"requires":[["cable.high"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Chin Up": {"requires":[["pullup.bar","rings"]],"recommended":[],"loadSource":"bodyweight","pattern":"v_pull"},
  "Pull Up": {"requires":[["pullup.bar","rings"]],"recommended":[],"loadSource":"bodyweight","pattern":"v_pull"},
  "Neutral Grip Pull Up": {"requires":[["pullup.bar","rings"]],"recommended":[],"loadSource":"bodyweight","pattern":"v_pull"},
  "Inverted Row": {"requires":[["rack","smith","rings","suspension"],["barbell","smith","rings","suspension"]],"recommended":[],"loadSource":"bodyweight","pattern":"h_pull"},
  "Face Pull": {"requires":[["cable.high","cable.mid"]],"recommended":[],"loadSource":"cable","pattern":"h_pull"},
  "Back Extension": {"requires":[["hyperext_bench","ghd"]],"recommended":[],"loadSource":"bodyweight","pattern":"hinge"},
  "Shrugs (hantle)": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Shrugs (sztanga)": {"requires":[["barbell"]],"recommended":["rack"],"loadSource":"barbell","pattern":"isolation"},
  "Good Morning": {"requires":[["barbell"],["rack"]],"recommended":["rack.safeties"],"loadSource":"barbell","pattern":"hinge"},
  "Overhead Press (sztanga)": {"requires":[["barbell"]],"recommended":["rack"],"loadSource":"barbell","pattern":"v_push"},
  "Overhead Press (hantle)": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"v_push","implements":2},
  "Seated Shoulder Press (hantle)": {"requires":[["db"],["bench.flat","bench.incline","box"]],"recommended":["bench.incline"],"loadSource":"dumbbell","pattern":"v_push","implements":2},
  "Arnold Press": {"requires":[["db"]],"recommended":["bench.incline"],"loadSource":"dumbbell","pattern":"v_push","implements":2},
  "Push Press": {"requires":[["barbell"]],"recommended":["rack"],"loadSource":"barbell","pattern":"v_push"},
  "Machine Shoulder Press": {"requires":[["shoulder_press_machine"]],"recommended":[],"loadSource":"machine_stack","pattern":"v_push"},
  "Wyciskanie nad głowę (linki)": {"requires":[["cable.dual"],["cable.low"]],"recommended":[],"loadSource":"cable","pattern":"v_push"},
  "Lateral Raise (hantle)": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Cable Lateral Raise": {"requires":[["cable.low"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Front Raise": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Rear Delt Raise (hantle)": {"requires":[["db"]],"recommended":["bench.incline"],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Reverse Fly (hantle)": {"requires":[["db"]],"recommended":["bench.incline"],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Reverse Pec Deck": {"requires":[["pec_deck"]],"recommended":[],"loadSource":"machine_stack","pattern":"isolation"},
  "Upright Row": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Biceps Curl (hantle)": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Barbell Curl": {"requires":[["barbell"]],"recommended":[],"loadSource":"barbell","pattern":"isolation"},
  "EZ Bar Curl": {"requires":[["ez_bar"]],"recommended":[],"loadSource":"ez_bar","pattern":"isolation"},
  "Hammer Curl": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Incline Curl (hantle)": {"requires":[["db"],["bench.incline"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Concentration Curl (hantle)": {"requires":[["db"],["bench.flat","bench.incline","box"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":1},
  "Preacher Curl": {"requires":[["db"],["preacher_bench"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Spider Curl": {"requires":[["db"],["bench.incline"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Cable Curl": {"requires":[["cable.low"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Skullcrusher (hantle)": {"requires":[["db"],["bench.flat"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Skullcrusher (EZ)": {"requires":[["ez_bar"],["bench.flat"]],"recommended":[],"loadSource":"ez_bar","pattern":"isolation"},
  "Triceps Dips (ławka)": {"requires":[["bench.flat","box"]],"recommended":[],"loadSource":"bodyweight","pattern":"v_push"},
  "Triceps Pushdown": {"requires":[["cable.high"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Overhead Triceps Extension (hantel)": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":1},
  "Cable Overhead Extension": {"requires":[["cable.high","cable.low"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Close Grip Bench Press": {"requires":[["barbell"],["bench.flat"],["rack","bench.uprights"]],"recommended":["rack.safeties"],"loadSource":"barbell","pattern":"h_push"},
  "Triceps Kickback": {"requires":[["db"]],"recommended":["bench.flat"],"loadSource":"dumbbell","pattern":"isolation","implements":1},
  "Back Squat": {"requires":[["barbell"],["rack"]],"recommended":["rack.safeties"],"loadSource":"barbell","pattern":"squat"},
  "Front Squat": {"requires":[["barbell"],["rack"]],"recommended":["rack.safeties"],"loadSource":"barbell","pattern":"squat"},
  "Goblet Squat": {"requires":[["db","kb"]],"recommended":[],"loadSource":"dumbbell","pattern":"squat","implements":1},
  "Przysiad z pasem (linki)": {"requires":[["cable.low"],["dip_belt"]],"recommended":[],"loadSource":"cable","pattern":"squat"},
  "Box Squat": {"requires":[["barbell"],["rack"],["bench.flat","box"]],"recommended":["rack.safeties"],"loadSource":"barbell","pattern":"squat"},
  "Hack Squat": {"requires":[["hack_squat"]],"recommended":[],"loadSource":"plate_loaded_machine","pattern":"squat"},
  "Leg Press": {"requires":[["leg_press"]],"recommended":[],"loadSource":"plate_loaded_machine","pattern":"squat"},
  "Bulgarian Split Squat (hantle)": {"requires":[["db"],["bench.flat","box"]],"recommended":[],"loadSource":"dumbbell","pattern":"lunge_single_leg","implements":2},
  "Lunges (hantle)": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"lunge_single_leg","implements":2},
  "Walking Lunges": {"requires":[],"recommended":["db"],"loadSource":"dumbbell","pattern":"lunge_single_leg","implements":2},
  "Reverse Lunge": {"requires":[],"recommended":["db"],"loadSource":"dumbbell","pattern":"lunge_single_leg","implements":2},
  "Step Up": {"requires":[["bench.flat","box"]],"recommended":["db"],"loadSource":"dumbbell","pattern":"lunge_single_leg","implements":2},
  "Leg Extension": {"requires":[["leg_ext"]],"recommended":[],"loadSource":"machine_stack","pattern":"isolation"},
  "Leg Curl": {"requires":[["leg_curl"]],"recommended":[],"loadSource":"machine_stack","pattern":"isolation"},
  "Lying Leg Curl": {"requires":[["leg_curl"]],"recommended":[],"loadSource":"machine_stack","pattern":"isolation"},
  "Nordic Curl": {"requires":[["ghd","glute_ham_raise","lat_pulldown","barbell"]],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"isolation"},
  "Pistol Squat": {"requires":[],"recommended":[],"loadSource":"bodyweight","pattern":"lunge_single_leg"},
  "Sissy Squat": {"requires":[],"recommended":[],"loadSource":"bodyweight","pattern":"isolation"},
  "Wall Sit": {"requires":[],"recommended":[],"loadSource":"bodyweight","pattern":"squat"},
  "Hip Thrust (sztanga)": {"requires":[["barbell"],["bench.flat","box"]],"recommended":[],"loadSource":"barbell","pattern":"hinge"},
  "Hip Thrust (hantel)": {"requires":[["db"],["bench.flat","box"]],"recommended":[],"loadSource":"dumbbell","pattern":"hinge","implements":1},
  "Glute Bridge": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"hinge"},
  "Cable Kickback": {"requires":[["cable.low"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Hip Abduction": {"requires":[["hip_abductor_adductor"]],"recommended":[],"loadSource":"machine_stack","pattern":"isolation"},
  "Hip Adduction": {"requires":[["hip_abductor_adductor"]],"recommended":[],"loadSource":"machine_stack","pattern":"isolation"},
  "Kettlebell Swing": {"requires":[["kb","db"]],"recommended":[],"loadSource":"kettlebell","pattern":"hinge","implements":1},
  "Standing Calf Raise": {"requires":[["calf_machine"]],"recommended":[],"loadSource":"machine_stack","pattern":"isolation"},
  "Seated Calf Raise": {"requires":[["calf_machine"]],"recommended":[],"loadSource":"plate_loaded_machine","pattern":"isolation"},
  "Łydki na stopniu": {"requires":[],"recommended":["box","db"],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Calf Press (leg press)": {"requires":[["leg_press"]],"recommended":[],"loadSource":"plate_loaded_machine","pattern":"isolation"},
  "Plank": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"core_anti_ext"},
  "Side Plank": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"core_other"},
  "Dead Bug": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"core_anti_ext"},
  "Bird Dog": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"core_anti_rot"},
  "Ab Wheel": {"requires":[["ab_wheel"]],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"core_anti_ext"},
  "Pallof Press": {"requires":[["cable.mid"]],"recommended":[],"loadSource":"cable","pattern":"core_anti_rot"},
  "Hanging Leg Raise": {"requires":[["pullup.bar","rings"]],"recommended":[],"loadSource":"bodyweight","pattern":"core_flexion"},
  "Hanging Knee Raise": {"requires":[["pullup.bar","rings","dip.bars"]],"recommended":[],"loadSource":"bodyweight","pattern":"core_flexion"},
  "Cable Crunch": {"requires":[["cable.high"]],"recommended":["floor_mat"],"loadSource":"cable","pattern":"core_flexion"},
  "Crunch": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"core_flexion"},
  "Reverse Crunch": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"core_flexion"},
  "Russian Twist": {"requires":[],"recommended":["db","floor_mat"],"loadSource":"dumbbell","pattern":"core_other","implements":1},
  "Hollow Hold": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"core_anti_ext"},
  "Farmer's Walk": {"requires":[["db","kb"]],"recommended":[],"loadSource":"dumbbell","pattern":"carry","implements":2},
  "Suitcase Carry": {"requires":[["db","kb"]],"recommended":[],"loadSource":"dumbbell","pattern":"carry","implements":1},
  "Mountain Climbers": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"cardio"},
  "Incline Walk (bieżnia)": {"requires":[["cardio.treadmill"]],"recommended":[],"loadSource":"none","pattern":"cardio"},
  "Bieg": {"requires":[],"recommended":[],"loadSource":"none","pattern":"cardio"},
  "Rower": {"requires":[["cardio.bike","outdoor"]],"recommended":[],"loadSource":"none","pattern":"cardio"},
  "Rowing Machine": {"requires":[["cardio.rower"]],"recommended":[],"loadSource":"none","pattern":"cardio"},
  "Assault Bike": {"requires":[["cardio.bike"]],"recommended":[],"loadSource":"none","pattern":"cardio"},
  "Skakanka": {"requires":[["jump_rope"]],"recommended":[],"loadSource":"none","pattern":"cardio"},
  "Burpees": {"requires":[],"recommended":[],"loadSource":"bodyweight","pattern":"cardio"},
  "Box Jump": {"requires":[["box"]],"recommended":[],"loadSource":"bodyweight","pattern":"other"},
  "Medicine Ball Slam": {"requires":[["med_ball"]],"recommended":[],"loadSource":"none","pattern":"other"},
  "Incline Chest Fly (hantle)": {"requires":[["db"],["bench.incline"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Decline Bench Press (hantle)": {"requires":[["db"],["bench.decline"]],"recommended":[],"loadSource":"dumbbell","pattern":"h_push","implements":2},
  "Floor Press (hantle)": {"requires":[["db"]],"recommended":["floor_mat"],"loadSource":"dumbbell","pattern":"h_push","implements":2},
  "Floor Press (sztanga)": {"requires":[["barbell"],["rack"]],"recommended":["rack.safeties"],"loadSource":"barbell","pattern":"h_push"},
  "Squeeze Press (hantle)": {"requires":[["db"],["bench.flat"]],"recommended":[],"loadSource":"dumbbell","pattern":"h_push","implements":2},
  "Cable Fly (low to high)": {"requires":[["cable.dual"],["cable.low"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Cable Fly (high to low)": {"requires":[["cable.dual"],["cable.high"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Incline Cable Fly": {"requires":[["cable.dual"],["cable.low"],["bench.incline"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Single Arm Cable Fly": {"requires":[["cable.mid","cable.low"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Single Arm Cable Chest Press": {"requires":[["cable.mid","cable.low"]],"recommended":[],"loadSource":"cable","pattern":"h_push"},
  "Svend Press": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":1},
  "Decline Push Up": {"requires":[["bench.flat","box"]],"recommended":[],"loadSource":"bodyweight","pattern":"h_push"},
  "Smith Machine Bench Press": {"requires":[["smith"],["bench.flat"]],"recommended":[],"loadSource":"smith","pattern":"h_push"},
  "Smith Machine Incline Press": {"requires":[["smith"],["bench.incline"]],"recommended":[],"loadSource":"smith","pattern":"h_push"},
  "Pullover (hantel)": {"requires":[["db"],["bench.flat"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":1},
  "Single Arm Cable Row": {"requires":[["cable.low","cable.mid","cable.row_seat"]],"recommended":[],"loadSource":"cable","pattern":"h_pull"},
  "Standing Cable Row": {"requires":[["cable.mid","cable.low"]],"recommended":[],"loadSource":"cable","pattern":"h_pull"},
  "Bent Over Row (linki)": {"requires":[["cable.dual"],["cable.low"]],"recommended":[],"loadSource":"cable","pattern":"h_pull"},
  "Meadows Row": {"requires":[["landmine"],["barbell"]],"recommended":[],"loadSource":"barbell","pattern":"h_pull"},
  "Seal Row (sztanga)": {"requires":[["barbell"],["bench.flat"]],"recommended":["box"],"loadSource":"barbell","pattern":"h_pull"},
  "Rack Pull": {"requires":[["barbell"],["rack.safeties"]],"recommended":[],"loadSource":"barbell","pattern":"hinge"},
  "Single Arm Lat Pulldown": {"requires":[["cable.high","lat_pulldown"]],"recommended":[],"loadSource":"cable","pattern":"v_pull"},
  "Renegade Row": {"requires":[["db"]],"recommended":["floor_mat"],"loadSource":"dumbbell","pattern":"h_pull","implements":2},
  "Superman": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"other"},
  "Shrugs (linki)": {"requires":[["cable.dual"],["cable.low"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Dead Hang": {"requires":[["pullup.bar","rings"]],"recommended":[],"loadSource":"bodyweight","pattern":"other"},
  "Landmine Press": {"requires":[["landmine"],["barbell"]],"recommended":[],"loadSource":"barbell","pattern":"v_push"},
  "Single Arm Overhead Press (hantel)": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"v_push","implements":1},
  "Cable Front Raise": {"requires":[["cable.low"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Cable Reverse Fly": {"requires":[["cable.dual"],["cable.high","cable.mid"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Y Raise (hantle)": {"requires":[["db"]],"recommended":["bench.incline"],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Cable Y Raise": {"requires":[["cable.dual"],["cable.low"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Upright Row (linki)": {"requires":[["cable.low"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Upright Row (sztanga)": {"requires":[["barbell","ez_bar"]],"recommended":[],"loadSource":"barbell","pattern":"isolation"},
  "Pike Push Up": {"requires":[],"recommended":[],"loadSource":"bodyweight","pattern":"v_push"},
  "Handstand Push Up": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"v_push"},
  "Kettlebell Press": {"requires":[["kb"]],"recommended":[],"loadSource":"kettlebell","pattern":"v_push","implements":1},
  "Smith Machine Shoulder Press": {"requires":[["smith"],["bench.flat","bench.incline","box"]],"recommended":["bench.incline"],"loadSource":"smith","pattern":"v_push"},
  "External Rotation (linki)": {"requires":[["cable.mid","cable.low"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "External Rotation (hantel)": {"requires":[["db"]],"recommended":["floor_mat","bench.flat"],"loadSource":"dumbbell","pattern":"isolation","implements":1},
  "Band Pull Apart": {"requires":[["bands"]],"recommended":[],"loadSource":"band","pattern":"h_pull"},
  "Hammer Curl (linki)": {"requires":[["cable.low"]],"recommended":["cable.rope"],"loadSource":"cable","pattern":"isolation"},
  "Bayesian Curl": {"requires":[["cable.low","cable.mid"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "High Cable Curl": {"requires":[["cable.dual"],["cable.high","cable.mid"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Cable Curl (dwie linki)": {"requires":[["cable.dual"],["cable.low"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Preacher Curl (EZ)": {"requires":[["ez_bar"],["preacher_bench"]],"recommended":[],"loadSource":"ez_bar","pattern":"isolation"},
  "Reverse Curl": {"requires":[["barbell","ez_bar"]],"recommended":[],"loadSource":"barbell","pattern":"isolation"},
  "Zottman Curl": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Wrist Curl (hantle)": {"requires":[["db"]],"recommended":["bench.flat"],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Reverse Wrist Curl (hantle)": {"requires":[["db"]],"recommended":["bench.flat"],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Single Arm Triceps Pushdown": {"requires":[["cable.high"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Triceps Kickback (linki)": {"requires":[["cable.low","cable.mid"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Overhead Triceps Extension (EZ)": {"requires":[["ez_bar"]],"recommended":["bench.flat"],"loadSource":"ez_bar","pattern":"isolation"},
  "Skullcrusher (sztanga)": {"requires":[["barbell"],["bench.flat"]],"recommended":[],"loadSource":"barbell","pattern":"isolation"},
  "JM Press": {"requires":[["barbell"],["bench.flat"],["rack","bench.uprights"]],"recommended":["rack.safeties"],"loadSource":"barbell","pattern":"h_push"},
  "Tate Press": {"requires":[["db"],["bench.flat"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Single Leg RDL (hantel)": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"hinge","implements":1},
  "Single Leg RDL (linki)": {"requires":[["cable.low"]],"recommended":[],"loadSource":"cable","pattern":"hinge"},
  "Cable Squat": {"requires":[["cable.dual"],["cable.low"]],"recommended":[],"loadSource":"cable","pattern":"squat"},
  "Single Leg Press": {"requires":[["leg_press"]],"recommended":[],"loadSource":"plate_loaded_machine","pattern":"lunge_single_leg"},
  "Split Squat": {"requires":[],"recommended":["db"],"loadSource":"dumbbell","pattern":"lunge_single_leg","implements":2},
  "Split Squat (linki)": {"requires":[["cable.dual"],["cable.low"]],"recommended":[],"loadSource":"cable","pattern":"lunge_single_leg"},
  "Lateral Lunge": {"requires":[],"recommended":["db"],"loadSource":"dumbbell","pattern":"lunge_single_leg","implements":2},
  "Curtsy Lunge": {"requires":[],"recommended":["db"],"loadSource":"dumbbell","pattern":"lunge_single_leg","implements":2},
  "Cossack Squat": {"requires":[],"recommended":[],"loadSource":"bodyweight","pattern":"lunge_single_leg"},
  "Bodyweight Squat": {"requires":[],"recommended":[],"loadSource":"bodyweight","pattern":"squat"},
  "Jump Squat": {"requires":[],"recommended":[],"loadSource":"bodyweight","pattern":"other"},
  "Smith Machine Squat": {"requires":[["smith"]],"recommended":[],"loadSource":"smith","pattern":"squat"},
  "Zercher Squat": {"requires":[["barbell"],["rack"]],"recommended":["rack.safeties"],"loadSource":"barbell","pattern":"squat"},
  "Double Kettlebell Front Squat": {"requires":[["kb"]],"recommended":[],"loadSource":"kettlebell","pattern":"squat","implements":2},
  "Landmine Squat": {"requires":[["landmine"],["barbell"]],"recommended":[],"loadSource":"barbell","pattern":"squat"},
  "Sumo Squat (hantel)": {"requires":[["db","kb"]],"recommended":[],"loadSource":"dumbbell","pattern":"squat","implements":1},
  "Lunges (sztanga)": {"requires":[["barbell"],["rack"]],"recommended":["rack.safeties"],"loadSource":"barbell","pattern":"lunge_single_leg"},
  "Reverse Nordic": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"isolation"},
  "Glute Ham Raise": {"requires":[["glute_ham_raise"]],"recommended":[],"loadSource":"bodyweight","pattern":"isolation"},
  "Standing Cable Leg Curl": {"requires":[["cable.low"]],"recommended":["ankle_strap"],"loadSource":"cable","pattern":"isolation"},
  "Leg Curl (hantel)": {"requires":[["db"],["bench.flat"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":1},
  "Cable Pull Through": {"requires":[["cable.low"]],"recommended":["cable.rope"],"loadSource":"cable","pattern":"hinge"},
  "Frog Pump": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"hinge"},
  "Single Leg Glute Bridge": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"hinge"},
  "Single Leg Hip Thrust": {"requires":[["bench.flat","box"]],"recommended":[],"loadSource":"bodyweight","pattern":"hinge"},
  "Glute Bridge (sztanga)": {"requires":[["barbell"]],"recommended":["floor_mat"],"loadSource":"barbell","pattern":"hinge"},
  "Smith Machine Hip Thrust": {"requires":[["smith"],["bench.flat","box"]],"recommended":[],"loadSource":"smith","pattern":"hinge"},
  "Sumo Deadlift (kettlebell)": {"requires":[["kb"]],"recommended":[],"loadSource":"kettlebell","pattern":"hinge","implements":1},
  "Cable Hip Abduction": {"requires":[["cable.low"]],"recommended":["ankle_strap"],"loadSource":"cable","pattern":"isolation"},
  "Lateral Band Walk": {"requires":[["bands"]],"recommended":[],"loadSource":"band","pattern":"isolation"},
  "Fire Hydrant": {"requires":[],"recommended":["floor_mat","bands"],"loadSource":"bodyweight","pattern":"isolation"},
  "Donkey Kick": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"isolation"},
  "Clamshell": {"requires":[],"recommended":["floor_mat","bands"],"loadSource":"bodyweight","pattern":"isolation"},
  "Single Leg Calf Raise": {"requires":[],"recommended":["box","db"],"loadSource":"dumbbell","pattern":"isolation","implements":1},
  "Seated Calf Raise (hantle)": {"requires":[["db"],["bench.flat","box"]],"recommended":["box"],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Smith Machine Calf Raise": {"requires":[["smith"]],"recommended":["box"],"loadSource":"smith","pattern":"isolation"},
  "Calf Raise (sztanga)": {"requires":[["barbell"],["rack"]],"recommended":["box"],"loadSource":"barbell","pattern":"isolation"},
  "Calf Raise (linki)": {"requires":[["cable.dual"],["cable.low"]],"recommended":["box"],"loadSource":"cable","pattern":"isolation"},
  "Cable Woodchop": {"requires":[["cable.high","cable.mid","cable.low"]],"recommended":[],"loadSource":"cable","pattern":"core_other"},
  "Landmine Rotation": {"requires":[["landmine"],["barbell"]],"recommended":[],"loadSource":"barbell","pattern":"core_other"},
  "Toes to Bar": {"requires":[["pullup.bar","rings"]],"recommended":[],"loadSource":"bodyweight","pattern":"core_flexion"},
  "L-Sit": {"requires":[],"recommended":["dip.bars"],"loadSource":"bodyweight","pattern":"core_flexion"},
  "Plank Shoulder Taps": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"core_anti_rot"},
  "Copenhagen Plank": {"requires":[["bench.flat","box"]],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"core_other"},
  "Decline Crunch": {"requires":[["bench.decline"]],"recommended":[],"loadSource":"bodyweight","pattern":"core_flexion"},
  "GHD Sit Up": {"requires":[["ghd"]],"recommended":[],"loadSource":"bodyweight","pattern":"core_flexion"},
  "Sit Up": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"core_flexion"},
  "V-Up": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"core_flexion"},
  "Bicycle Crunch": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"core_flexion"},
  "Lying Leg Raise": {"requires":[],"recommended":["floor_mat","bench.flat"],"loadSource":"bodyweight","pattern":"core_flexion"},
  "Dragon Flag": {"requires":[["bench.flat"]],"recommended":[],"loadSource":"bodyweight","pattern":"core_anti_ext"},
  "Rollout (sztanga)": {"requires":[["barbell"]],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"core_anti_ext"},
  "Side Bend (hantel)": {"requires":[["db","kb"]],"recommended":[],"loadSource":"dumbbell","pattern":"core_other","implements":1},
  "Kettlebell Windmill": {"requires":[["kb"]],"recommended":[],"loadSource":"kettlebell","pattern":"core_other","implements":1},
  "Turkish Get Up": {"requires":[["kb","db"]],"recommended":["floor_mat"],"loadSource":"kettlebell","pattern":"other","implements":1},
  "Overhead Carry (hantle)": {"requires":[["db","kb"]],"recommended":[],"loadSource":"dumbbell","pattern":"carry","implements":2},
  "Double Kettlebell Front Rack Carry": {"requires":[["kb"]],"recommended":[],"loadSource":"kettlebell","pattern":"carry","implements":2},
  "Farmer's Walk (trap bar)": {"requires":[["trap_bar"]],"recommended":[],"loadSource":"trap_bar","pattern":"carry"},
  "Kettlebell Clean": {"requires":[["kb"]],"recommended":[],"loadSource":"kettlebell","pattern":"hinge","implements":1},
  "Kettlebell Snatch": {"requires":[["kb"]],"recommended":[],"loadSource":"kettlebell","pattern":"hinge","implements":1},
  "Snatch (hantel)": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"hinge","implements":1},
  "Power Clean": {"requires":[["barbell"]],"recommended":[],"loadSource":"barbell","pattern":"hinge"},
  "Thruster (hantle)": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"squat","implements":2},
  "Wall Ball": {"requires":[["med_ball"]],"recommended":[],"loadSource":"none","pattern":"other"},
  "Jumping Jacks": {"requires":[],"recommended":[],"loadSource":"bodyweight","pattern":"cardio"},
  "High Knees": {"requires":[],"recommended":[],"loadSource":"bodyweight","pattern":"cardio"},
  "Broad Jump": {"requires":[],"recommended":[],"loadSource":"bodyweight","pattern":"other"},
  "Single Arm RDL (hantel/linka)": {"requires":[["db","cable.low"]],"recommended":[],"loadSource":"dumbbell","pattern":"hinge","implements":1},
  "Cable Hip Adduction": {"requires":[["cable.low"]],"recommended":["ankle_strap"],"loadSource":"cable","pattern":"isolation"},
  "Machine Row": {"requires":[["row_machine"]],"recommended":[],"loadSource":"machine_stack","pattern":"h_pull"},
  "Machine Pullover": {"requires":[["pullover_machine"]],"recommended":[],"loadSource":"machine_stack","pattern":"isolation"},
  "Machine Crunch": {"requires":[["ab_crunch_machine"]],"recommended":[],"loadSource":"machine_stack","pattern":"core_flexion"},
  "Machine Biceps Curl": {"requires":[["biceps_curl_machine"]],"recommended":[],"loadSource":"machine_stack","pattern":"isolation"},
  "Machine Triceps Extension": {"requires":[["triceps_ext_machine"]],"recommended":[],"loadSource":"machine_stack","pattern":"isolation"},
  "Machine Lateral Raise": {"requires":[["lateral_raise_machine"]],"recommended":[],"loadSource":"machine_stack","pattern":"isolation"},
  "Machine Glute Kickback": {"requires":[["glute_kickback_machine"]],"recommended":[],"loadSource":"machine_stack","pattern":"isolation"},
  "Machine Hip Thrust": {"requires":[["hip_thrust_machine"]],"recommended":[],"loadSource":"plate_loaded_machine","pattern":"hinge"},
  "Belt Squat Machine": {"requires":[["belt_squat_machine"]],"recommended":[],"loadSource":"plate_loaded_machine","pattern":"squat"},
  "Pendulum Squat": {"requires":[["pendulum_squat"]],"recommended":[],"loadSource":"plate_loaded_machine","pattern":"squat"},
  "Reverse Hyperextension": {"requires":[["reverse_hyper"]],"recommended":[],"loadSource":"plate_loaded_machine","pattern":"hinge"},
  "Sled Push": {"requires":[["sled"]],"recommended":[],"loadSource":"none","pattern":"other"},
  "Battle Ropes": {"requires":[["battle_ropes"]],"recommended":[],"loadSource":"none","pattern":"cardio"},
  "Stair Climber": {"requires":[["cardio.stair"]],"recommended":[],"loadSource":"none","pattern":"cardio"},
  "Orbitrek": {"requires":[["cardio.elliptical"]],"recommended":[],"loadSource":"none","pattern":"cardio"},
  "Ski Erg": {"requires":[["cardio.ski"]],"recommended":[],"loadSource":"none","pattern":"cardio"},
  "Stability Ball Crunch": {"requires":[["stability_ball"]],"recommended":[],"loadSource":"none","pattern":"core_flexion"},
  "Stability Ball Hamstring Curl": {"requires":[["stability_ball"]],"recommended":["floor_mat"],"loadSource":"none","pattern":"isolation"},
  "Slider Hamstring Curl": {"requires":[["sliders"]],"recommended":["floor_mat"],"loadSource":"none","pattern":"isolation"},
  "Slider Reverse Lunge": {"requires":[["sliders"]],"recommended":[],"loadSource":"none","pattern":"lunge_single_leg"},
};
/** Regiony mięśni (obciążenie partii) → zgrubna partia z lib/seed.ts MUSCLES (null = bez odpowiednika). */
export const MUSCLE_REGIONS = {"chest":"klatka","front_delt":"barki","side_delt":"barki","rear_delt":"barki","lats":"plecy","upper_back":"plecy","lower_back":"plecy","biceps":"biceps","triceps":"triceps","forearms":"przedramiona","abs":"core","obliques":"core","glutes":"pośladki","quads":"czworogłowe","hamstrings":"dwugłowe","adductors":"przywodziciele","abductors":"pośladki","calves":"łydki"} as const;
export type MuscleRegion = keyof typeof MUSCLE_REGIONS;
/** Obciążenie partii przez ćwiczenie: 1 = główny, 0,5 = znaczący pomocniczy, 0,25 = stabilizacja. */
export const MUSCLE_LOAD: Readonly<Record<string, Partial<Record<MuscleRegion, number>>>> = {
  "Bench Press (sztanga)": {"chest":1,"triceps":0.5,"front_delt":0.5},
  "Bench Press (hantle)": {"chest":1,"triceps":0.5,"front_delt":0.5},
  "Incline Bench Press (sztanga)": {"chest":1,"front_delt":0.5,"triceps":0.5},
  "Incline Bench Press (hantle)": {"chest":1,"front_delt":0.5,"triceps":0.5},
  "Decline Bench Press": {"chest":1,"triceps":0.5,"front_delt":0.25},
  "Chest Fly (hantle)": {"chest":1,"front_delt":0.5,"biceps":0.25},
  "Cable Fly": {"chest":1,"front_delt":0.5,"biceps":0.25},
  "Pec Deck": {"chest":1,"front_delt":0.5},
  "Machine Chest Press": {"chest":1,"triceps":0.5,"front_delt":0.5},
  "Wyciskanie na linkach (stojąc)": {"chest":1,"triceps":0.5,"front_delt":0.5,"abs":0.25},
  "Chest Dip": {"chest":1,"triceps":0.5,"front_delt":0.5},
  "Push Up": {"chest":1,"triceps":0.5,"front_delt":0.5,"abs":0.25},
  "Incline Push Up": {"chest":1,"triceps":0.5,"front_delt":0.5,"abs":0.25},
  "Diamond Push Up": {"triceps":1,"chest":0.5,"front_delt":0.5,"abs":0.25},
  "Deadlift (sztanga)": {"lower_back":1,"hamstrings":1,"glutes":0.5,"quads":0.5,"upper_back":0.5,"forearms":0.5,"lats":0.25,"adductors":0.25,"abs":0.25},
  "Deadlift (hantle)": {"lower_back":1,"hamstrings":1,"glutes":0.5,"quads":0.25,"upper_back":0.25,"forearms":0.5,"lats":0.25},
  "Sumo Deadlift": {"glutes":1,"quads":1,"lower_back":0.5,"hamstrings":0.5,"adductors":0.5,"upper_back":0.5,"forearms":0.5},
  "Trap Bar Deadlift": {"quads":1,"lower_back":1,"glutes":0.5,"hamstrings":0.5,"upper_back":0.5,"forearms":0.5},
  "RDL (sztanga)": {"hamstrings":1,"glutes":0.5,"lower_back":0.5,"upper_back":0.25,"forearms":0.25,"adductors":0.25},
  "RDL (hantle/linki)": {"hamstrings":1,"glutes":0.5,"lower_back":0.5,"upper_back":0.25,"forearms":0.25,"adductors":0.25},
  "Bent Over Row (sztanga)": {"lats":1,"upper_back":1,"rear_delt":0.5,"biceps":0.5,"lower_back":0.5,"forearms":0.25},
  "Bent Over Row (hantle)": {"lats":1,"upper_back":1,"rear_delt":0.5,"biceps":0.5,"lower_back":0.5,"forearms":0.25},
  "Pendlay Row": {"lats":1,"upper_back":1,"rear_delt":0.5,"biceps":0.5,"lower_back":0.5,"forearms":0.25},
  "One Arm Row (hantle)": {"lats":1,"upper_back":0.5,"rear_delt":0.5,"biceps":0.5,"forearms":0.25,"obliques":0.25},
  "Chest Supported Row": {"lats":1,"upper_back":1,"rear_delt":0.5,"biceps":0.5,"forearms":0.25},
  "T-Bar Row": {"lats":1,"upper_back":1,"rear_delt":0.5,"biceps":0.5,"lower_back":0.5,"forearms":0.25},
  "Seated Cable Row": {"lats":1,"upper_back":1,"rear_delt":0.5,"biceps":0.5,"forearms":0.25,"lower_back":0.25},
  "Wiosłowanie na linkach (siedząc)": {"lats":1,"upper_back":1,"rear_delt":0.5,"biceps":0.5,"forearms":0.25,"lower_back":0.25},
  "Lat Pulldown": {"lats":1,"upper_back":0.5,"biceps":0.5,"rear_delt":0.25,"forearms":0.25},
  "Straight Arm Pulldown": {"lats":1,"triceps":0.25,"rear_delt":0.25,"abs":0.25},
  "Chin Up": {"lats":1,"biceps":0.5,"upper_back":0.5,"forearms":0.5,"rear_delt":0.25,"abs":0.25},
  "Pull Up": {"lats":1,"upper_back":0.5,"biceps":0.5,"forearms":0.5,"rear_delt":0.25,"abs":0.25},
  "Neutral Grip Pull Up": {"lats":1,"upper_back":0.5,"biceps":0.5,"forearms":0.5,"rear_delt":0.25,"abs":0.25},
  "Inverted Row": {"upper_back":1,"lats":1,"rear_delt":0.5,"biceps":0.5,"abs":0.25,"glutes":0.25},
  "Face Pull": {"rear_delt":1,"upper_back":0.5,"side_delt":0.25,"biceps":0.25},
  "Back Extension": {"lower_back":1,"glutes":0.5,"hamstrings":0.5},
  "Shrugs (hantle)": {"upper_back":1,"forearms":0.5},
  "Shrugs (sztanga)": {"upper_back":1,"forearms":0.5},
  "Good Morning": {"hamstrings":1,"lower_back":0.5,"glutes":0.5,"abs":0.25},
  "Overhead Press (sztanga)": {"front_delt":1,"side_delt":0.5,"triceps":0.5,"upper_back":0.25,"chest":0.25,"abs":0.25},
  "Overhead Press (hantle)": {"front_delt":1,"side_delt":0.5,"triceps":0.5,"upper_back":0.25,"abs":0.25},
  "Seated Shoulder Press (hantle)": {"front_delt":1,"side_delt":0.5,"triceps":0.5,"upper_back":0.25},
  "Arnold Press": {"front_delt":1,"side_delt":0.5,"triceps":0.5,"upper_back":0.25},
  "Push Press": {"front_delt":1,"side_delt":0.5,"triceps":0.5,"quads":0.5,"glutes":0.25,"upper_back":0.25,"abs":0.25,"calves":0.25},
  "Machine Shoulder Press": {"front_delt":1,"side_delt":0.5,"triceps":0.5},
  "Wyciskanie nad głowę (linki)": {"front_delt":1,"side_delt":0.5,"triceps":0.5,"upper_back":0.25,"abs":0.25},
  "Lateral Raise (hantle)": {"side_delt":1,"front_delt":0.25,"upper_back":0.25},
  "Cable Lateral Raise": {"side_delt":1,"front_delt":0.25,"upper_back":0.25},
  "Front Raise": {"front_delt":1,"side_delt":0.25,"chest":0.25},
  "Rear Delt Raise (hantle)": {"rear_delt":1,"upper_back":0.5},
  "Reverse Fly (hantle)": {"rear_delt":1,"upper_back":0.5},
  "Reverse Pec Deck": {"rear_delt":1,"upper_back":0.5},
  "Upright Row": {"side_delt":1,"upper_back":0.5,"front_delt":0.5,"biceps":0.5,"forearms":0.25},
  "Biceps Curl (hantle)": {"biceps":1,"forearms":0.25},
  "Barbell Curl": {"biceps":1,"forearms":0.25},
  "EZ Bar Curl": {"biceps":1,"forearms":0.25},
  "Hammer Curl": {"biceps":1,"forearms":0.5},
  "Incline Curl (hantle)": {"biceps":1,"forearms":0.25},
  "Concentration Curl (hantle)": {"biceps":1,"forearms":0.25},
  "Preacher Curl": {"biceps":1,"forearms":0.25},
  "Spider Curl": {"biceps":1,"forearms":0.25},
  "Cable Curl": {"biceps":1,"forearms":0.25},
  "Skullcrusher (hantle)": {"triceps":1},
  "Skullcrusher (EZ)": {"triceps":1},
  "Triceps Dips (ławka)": {"triceps":1,"chest":0.5,"front_delt":0.5},
  "Triceps Pushdown": {"triceps":1},
  "Overhead Triceps Extension (hantel)": {"triceps":1},
  "Cable Overhead Extension": {"triceps":1},
  "Close Grip Bench Press": {"triceps":1,"chest":0.5,"front_delt":0.5},
  "Triceps Kickback": {"triceps":1,"rear_delt":0.25},
  "Back Squat": {"quads":1,"glutes":0.5,"hamstrings":0.5,"adductors":0.5,"lower_back":0.5,"abs":0.25,"calves":0.25},
  "Front Squat": {"quads":1,"glutes":0.5,"abs":0.5,"upper_back":0.5,"adductors":0.5,"lower_back":0.25},
  "Goblet Squat": {"quads":1,"glutes":0.5,"adductors":0.5,"abs":0.25,"upper_back":0.25},
  "Przysiad z pasem (linki)": {"quads":1,"glutes":0.5,"adductors":0.5,"hamstrings":0.25},
  "Box Squat": {"quads":1,"glutes":0.5,"hamstrings":0.5,"adductors":0.5,"lower_back":0.5},
  "Hack Squat": {"quads":1,"glutes":0.5,"adductors":0.25},
  "Leg Press": {"quads":1,"glutes":0.5,"adductors":0.5,"hamstrings":0.25},
  "Bulgarian Split Squat (hantle)": {"quads":1,"glutes":1,"hamstrings":0.5,"adductors":0.5,"abductors":0.25,"calves":0.25,"forearms":0.25},
  "Lunges (hantle)": {"quads":1,"glutes":1,"adductors":0.5,"hamstrings":0.25,"abductors":0.25,"calves":0.25,"forearms":0.25},
  "Walking Lunges": {"quads":1,"glutes":1,"adductors":0.5,"hamstrings":0.25,"abductors":0.25,"calves":0.25,"forearms":0.25},
  "Reverse Lunge": {"quads":1,"glutes":1,"adductors":0.5,"hamstrings":0.25,"abductors":0.25,"calves":0.25,"forearms":0.25},
  "Step Up": {"quads":1,"glutes":1,"hamstrings":0.25,"abductors":0.25,"calves":0.25,"forearms":0.25},
  "Leg Extension": {"quads":1},
  "Leg Curl": {"hamstrings":1,"calves":0.25},
  "Lying Leg Curl": {"hamstrings":1,"calves":0.25},
  "Nordic Curl": {"hamstrings":1,"calves":0.25,"glutes":0.25},
  "Pistol Squat": {"quads":1,"glutes":0.5,"adductors":0.25,"abductors":0.25,"abs":0.25,"calves":0.25},
  "Sissy Squat": {"quads":1,"abs":0.25},
  "Wall Sit": {"quads":1,"glutes":0.25},
  "Hip Thrust (sztanga)": {"glutes":1,"hamstrings":0.5,"quads":0.25,"adductors":0.25,"abductors":0.25},
  "Hip Thrust (hantel)": {"glutes":1,"hamstrings":0.5,"quads":0.25,"adductors":0.25,"abductors":0.25},
  "Glute Bridge": {"glutes":1,"hamstrings":0.5},
  "Cable Kickback": {"glutes":1,"hamstrings":0.5,"abductors":0.25},
  "Hip Abduction": {"abductors":1,"glutes":0.5},
  "Hip Adduction": {"adductors":1,"glutes":0.25},
  "Kettlebell Swing": {"glutes":1,"hamstrings":1,"lower_back":0.5,"abs":0.25,"forearms":0.25,"front_delt":0.25,"quads":0.25},
  "Standing Calf Raise": {"calves":1},
  "Seated Calf Raise": {"calves":1},
  "Łydki na stopniu": {"calves":1,"forearms":0.25},
  "Calf Press (leg press)": {"calves":1},
  "Plank": {"abs":1,"obliques":0.5,"front_delt":0.25,"glutes":0.25,"quads":0.25},
  "Side Plank": {"obliques":1,"abs":0.5,"abductors":0.5,"side_delt":0.25},
  "Dead Bug": {"abs":1,"obliques":0.5},
  "Bird Dog": {"obliques":1,"abs":0.5,"lower_back":1,"glutes":0.5,"front_delt":0.25,"upper_back":0.25},
  "Ab Wheel": {"abs":1,"obliques":0.5,"lats":0.5,"triceps":0.25,"front_delt":0.25},
  "Pallof Press": {"obliques":1,"abs":0.5,"front_delt":0.25,"glutes":0.25},
  "Hanging Leg Raise": {"abs":1,"obliques":0.5,"forearms":0.5,"lats":0.25},
  "Hanging Knee Raise": {"abs":1,"obliques":0.5,"forearms":0.5,"lats":0.25},
  "Cable Crunch": {"abs":1,"obliques":0.5},
  "Crunch": {"abs":1,"obliques":0.25},
  "Reverse Crunch": {"abs":1,"obliques":0.25},
  "Russian Twist": {"obliques":1,"abs":0.5},
  "Hollow Hold": {"abs":1,"obliques":0.5},
  "Farmer's Walk": {"forearms":1,"upper_back":1,"obliques":0.5,"abs":0.5,"quads":0.25,"glutes":0.25,"calves":0.25},
  "Suitcase Carry": {"obliques":1,"forearms":0.5,"upper_back":0.5,"abs":0.5,"abductors":0.5},
  "Mountain Climbers": {"abs":1,"obliques":0.25,"front_delt":0.25,"chest":0.25,"triceps":0.25,"quads":0.25},
  "Incline Walk (bieżnia)": {"glutes":0.5,"hamstrings":0.5,"calves":0.5,"quads":0.5},
  "Bieg": {"quads":0.5,"hamstrings":0.5,"glutes":0.5,"calves":0.5,"abs":0.25},
  "Rower": {"quads":0.5,"glutes":0.5,"hamstrings":0.25,"calves":0.25},
  "Rowing Machine": {"quads":0.5,"glutes":0.5,"lats":0.5,"upper_back":0.5,"hamstrings":0.25,"lower_back":0.25,"biceps":0.25,"rear_delt":0.25,"forearms":0.25,"abs":0.25},
  "Assault Bike": {"quads":0.5,"glutes":0.5,"hamstrings":0.25,"chest":0.25,"lats":0.25,"front_delt":0.25,"triceps":0.25,"biceps":0.25},
  "Skakanka": {"calves":0.5,"quads":0.25,"forearms":0.25,"front_delt":0.25,"abs":0.25},
  "Burpees": {"quads":0.5,"glutes":0.5,"chest":0.5,"triceps":0.25,"front_delt":0.25,"abs":0.25,"hamstrings":0.25,"calves":0.25},
  "Box Jump": {"quads":0.5,"glutes":0.5,"calves":0.5,"hamstrings":0.25},
  "Medicine Ball Slam": {"lats":0.5,"abs":0.5,"front_delt":0.25,"triceps":0.25,"obliques":0.25,"glutes":0.25,"quads":0.25},
  "Incline Chest Fly (hantle)": {"chest":1,"front_delt":0.5,"biceps":0.25},
  "Decline Bench Press (hantle)": {"chest":1,"triceps":0.5,"front_delt":0.25},
  "Floor Press (hantle)": {"chest":1,"triceps":0.5,"front_delt":0.5},
  "Floor Press (sztanga)": {"chest":1,"triceps":0.5,"front_delt":0.5},
  "Squeeze Press (hantle)": {"chest":1,"triceps":0.5,"front_delt":0.25},
  "Cable Fly (low to high)": {"chest":1,"front_delt":0.5},
  "Cable Fly (high to low)": {"chest":1,"front_delt":0.25},
  "Incline Cable Fly": {"chest":1,"front_delt":0.5},
  "Single Arm Cable Fly": {"chest":1,"front_delt":0.25,"obliques":0.25},
  "Single Arm Cable Chest Press": {"chest":1,"triceps":0.5,"front_delt":0.5,"obliques":0.25},
  "Svend Press": {"chest":1,"front_delt":0.5},
  "Decline Push Up": {"chest":1,"front_delt":0.5,"triceps":0.5,"abs":0.25},
  "Smith Machine Bench Press": {"chest":1,"triceps":0.5,"front_delt":0.5},
  "Smith Machine Incline Press": {"chest":1,"front_delt":0.5,"triceps":0.5},
  "Pullover (hantel)": {"chest":1,"lats":1,"triceps":0.25},
  "Single Arm Cable Row": {"lats":1,"upper_back":1,"biceps":0.5,"rear_delt":0.5},
  "Standing Cable Row": {"upper_back":1,"lats":1,"biceps":0.5,"rear_delt":0.5,"lower_back":0.25},
  "Bent Over Row (linki)": {"lats":1,"upper_back":1,"biceps":0.5,"rear_delt":0.5,"lower_back":0.5,"hamstrings":0.25},
  "Meadows Row": {"lats":1,"upper_back":1,"biceps":0.5,"rear_delt":0.5,"forearms":0.25},
  "Seal Row (sztanga)": {"upper_back":1,"lats":1,"biceps":0.5,"rear_delt":0.5},
  "Rack Pull": {"upper_back":1,"lower_back":1,"glutes":0.5,"hamstrings":0.5,"forearms":0.5,"lats":0.25},
  "Single Arm Lat Pulldown": {"lats":1,"biceps":0.5,"upper_back":0.5},
  "Renegade Row": {"lats":1,"upper_back":1,"abs":1,"obliques":0.5,"biceps":0.5,"chest":0.25,"triceps":0.25},
  "Superman": {"lower_back":1,"glutes":0.5,"hamstrings":0.25,"upper_back":0.25},
  "Shrugs (linki)": {"upper_back":1,"forearms":0.25},
  "Dead Hang": {"forearms":1,"lats":0.5,"upper_back":0.25},
  "Landmine Press": {"front_delt":1,"chest":0.5,"triceps":0.5,"obliques":0.25},
  "Single Arm Overhead Press (hantel)": {"front_delt":1,"side_delt":0.5,"triceps":0.5,"obliques":0.25},
  "Cable Front Raise": {"front_delt":1,"side_delt":0.25,"upper_back":0.25},
  "Cable Reverse Fly": {"rear_delt":1,"upper_back":0.5},
  "Y Raise (hantle)": {"side_delt":1,"rear_delt":0.5,"upper_back":0.5},
  "Cable Y Raise": {"side_delt":1,"rear_delt":0.5,"upper_back":0.5},
  "Upright Row (linki)": {"side_delt":1,"upper_back":0.5,"front_delt":0.5,"biceps":0.25},
  "Upright Row (sztanga)": {"side_delt":1,"upper_back":0.5,"front_delt":0.5,"biceps":0.25},
  "Pike Push Up": {"front_delt":1,"triceps":0.5,"chest":0.25,"upper_back":0.25},
  "Handstand Push Up": {"front_delt":1,"triceps":0.5,"side_delt":0.5,"upper_back":0.25},
  "Kettlebell Press": {"front_delt":1,"triceps":0.5,"side_delt":0.5,"obliques":0.25},
  "Smith Machine Shoulder Press": {"front_delt":1,"triceps":0.5,"side_delt":0.5},
  "External Rotation (linki)": {"rear_delt":1,"upper_back":0.25},
  "External Rotation (hantel)": {"rear_delt":1,"upper_back":0.25},
  "Band Pull Apart": {"rear_delt":1,"upper_back":0.5},
  "Hammer Curl (linki)": {"biceps":1,"forearms":0.5},
  "Bayesian Curl": {"biceps":1,"forearms":0.25},
  "High Cable Curl": {"biceps":1,"forearms":0.25},
  "Cable Curl (dwie linki)": {"biceps":1,"forearms":0.25},
  "Preacher Curl (EZ)": {"biceps":1,"forearms":0.25},
  "Reverse Curl": {"biceps":1,"forearms":1},
  "Zottman Curl": {"biceps":1,"forearms":0.5},
  "Wrist Curl (hantle)": {"forearms":1},
  "Reverse Wrist Curl (hantle)": {"forearms":1},
  "Single Arm Triceps Pushdown": {"triceps":1},
  "Triceps Kickback (linki)": {"triceps":1,"rear_delt":0.25},
  "Overhead Triceps Extension (EZ)": {"triceps":1},
  "Skullcrusher (sztanga)": {"triceps":1},
  "JM Press": {"triceps":1,"chest":0.5,"front_delt":0.25},
  "Tate Press": {"triceps":1,"chest":0.25},
  "Single Leg RDL (hantel)": {"hamstrings":1,"glutes":1,"lower_back":0.5,"abductors":0.25},
  "Single Leg RDL (linki)": {"hamstrings":1,"glutes":1,"lower_back":0.5,"abductors":0.25},
  "Cable Squat": {"quads":1,"glutes":0.5,"adductors":0.25,"lower_back":0.25},
  "Single Leg Press": {"quads":1,"glutes":0.5,"hamstrings":0.25},
  "Split Squat": {"quads":1,"glutes":1,"adductors":0.25,"hamstrings":0.25},
  "Split Squat (linki)": {"quads":1,"glutes":1,"adductors":0.25},
  "Lateral Lunge": {"quads":1,"glutes":1,"adductors":0.5},
  "Curtsy Lunge": {"glutes":1,"quads":1,"abductors":0.25,"adductors":0.25},
  "Cossack Squat": {"quads":1,"glutes":1,"adductors":0.5,"hamstrings":0.25},
  "Bodyweight Squat": {"quads":1,"glutes":0.5},
  "Jump Squat": {"quads":1,"glutes":0.5,"calves":0.5},
  "Smith Machine Squat": {"quads":1,"glutes":0.5,"adductors":0.25},
  "Zercher Squat": {"quads":1,"glutes":0.5,"abs":0.5,"upper_back":0.5,"biceps":0.25},
  "Double Kettlebell Front Squat": {"quads":1,"glutes":0.5,"abs":0.5,"upper_back":0.25},
  "Landmine Squat": {"quads":1,"glutes":0.5,"abs":0.25},
  "Sumo Squat (hantel)": {"quads":1,"glutes":1,"adductors":0.5},
  "Lunges (sztanga)": {"quads":1,"glutes":1,"adductors":0.25,"hamstrings":0.25},
  "Reverse Nordic": {"quads":1,"abs":0.25},
  "Glute Ham Raise": {"hamstrings":1,"glutes":0.5,"calves":0.25},
  "Standing Cable Leg Curl": {"hamstrings":1,"calves":0.25},
  "Leg Curl (hantel)": {"hamstrings":1,"calves":0.25},
  "Cable Pull Through": {"glutes":1,"hamstrings":0.5,"lower_back":0.25},
  "Frog Pump": {"glutes":1,"abductors":0.25},
  "Single Leg Glute Bridge": {"glutes":1,"hamstrings":0.5},
  "Single Leg Hip Thrust": {"glutes":1,"hamstrings":0.5,"quads":0.25},
  "Glute Bridge (sztanga)": {"glutes":1,"hamstrings":0.5,"quads":0.25},
  "Smith Machine Hip Thrust": {"glutes":1,"hamstrings":0.5,"quads":0.25},
  "Sumo Deadlift (kettlebell)": {"glutes":1,"quads":1,"hamstrings":0.5,"adductors":0.5,"lower_back":0.25},
  "Cable Hip Abduction": {"abductors":1,"glutes":0.5},
  "Lateral Band Walk": {"abductors":1,"glutes":0.5},
  "Fire Hydrant": {"abductors":1,"glutes":0.5},
  "Donkey Kick": {"glutes":1,"hamstrings":0.5},
  "Clamshell": {"abductors":1,"glutes":0.5},
  "Single Leg Calf Raise": {"calves":1},
  "Seated Calf Raise (hantle)": {"calves":1},
  "Smith Machine Calf Raise": {"calves":1},
  "Calf Raise (sztanga)": {"calves":1},
  "Calf Raise (linki)": {"calves":1},
  "Cable Woodchop": {"obliques":1,"abs":0.5,"front_delt":0.25},
  "Landmine Rotation": {"obliques":1,"abs":0.5,"front_delt":0.5},
  "Toes to Bar": {"abs":1,"obliques":0.5,"lats":0.25,"forearms":0.25},
  "L-Sit": {"abs":1,"quads":0.25,"triceps":0.25},
  "Plank Shoulder Taps": {"abs":1,"obliques":0.5,"front_delt":0.25},
  "Copenhagen Plank": {"adductors":1,"obliques":0.5},
  "Decline Crunch": {"abs":1,"obliques":0.25},
  "GHD Sit Up": {"abs":1,"quads":0.25},
  "Sit Up": {"abs":1,"obliques":0.25},
  "V-Up": {"abs":1,"obliques":0.25},
  "Bicycle Crunch": {"abs":1,"obliques":1},
  "Lying Leg Raise": {"abs":1,"obliques":0.25},
  "Dragon Flag": {"abs":1,"obliques":0.5,"lats":0.25},
  "Rollout (sztanga)": {"abs":1,"lats":0.5,"obliques":0.25},
  "Side Bend (hantel)": {"obliques":1,"abs":0.25},
  "Kettlebell Windmill": {"obliques":1,"side_delt":0.5,"hamstrings":0.25,"glutes":0.25},
  "Turkish Get Up": {"abs":1,"obliques":1,"front_delt":1,"glutes":0.5,"triceps":0.25,"quads":0.25},
  "Overhead Carry (hantle)": {"abs":1,"front_delt":1,"side_delt":0.5,"upper_back":0.5,"triceps":0.25},
  "Double Kettlebell Front Rack Carry": {"abs":1,"upper_back":0.5,"biceps":0.25,"forearms":0.25},
  "Farmer's Walk (trap bar)": {"forearms":1,"upper_back":1,"abs":0.5,"obliques":0.5,"quads":0.25,"glutes":0.25,"calves":0.25},
  "Kettlebell Clean": {"glutes":1,"hamstrings":1,"upper_back":0.5,"lower_back":0.5,"forearms":0.25},
  "Kettlebell Snatch": {"glutes":1,"front_delt":1,"hamstrings":0.5,"upper_back":0.5,"lower_back":0.5},
  "Snatch (hantel)": {"glutes":1,"front_delt":1,"hamstrings":0.5,"quads":0.5,"upper_back":0.5},
  "Power Clean": {"glutes":1,"quads":1,"hamstrings":0.5,"upper_back":0.5,"lower_back":0.5,"calves":0.25},
  "Thruster (hantle)": {"quads":1,"front_delt":1,"glutes":0.5,"triceps":0.5},
  "Wall Ball": {"quads":1,"front_delt":0.5,"glutes":0.5,"triceps":0.25},
  "Jumping Jacks": {"calves":0.5,"side_delt":0.25,"abductors":0.25},
  "High Knees": {"quads":0.5,"calves":0.5,"abs":0.25},
  "Broad Jump": {"quads":1,"glutes":1,"calves":0.5,"hamstrings":0.25},
  "Single Arm RDL (hantel/linka)": {"hamstrings":1,"glutes":0.5,"lower_back":0.5,"obliques":0.25,"forearms":0.25,"adductors":0.25},
  "Cable Hip Adduction": {"adductors":1,"obliques":0.25},
  "Machine Row": {"lats":1,"upper_back":1,"rear_delt":0.5,"biceps":0.5,"forearms":0.25},
  "Machine Pullover": {"lats":1,"chest":0.25,"triceps":0.25},
  "Machine Crunch": {"abs":1,"obliques":0.25},
  "Machine Biceps Curl": {"biceps":1,"forearms":0.25},
  "Machine Triceps Extension": {"triceps":1},
  "Machine Lateral Raise": {"side_delt":1,"upper_back":0.25},
  "Machine Glute Kickback": {"glutes":1,"hamstrings":0.25},
  "Machine Hip Thrust": {"glutes":1,"hamstrings":0.25,"quads":0.25},
  "Belt Squat Machine": {"quads":1,"glutes":0.5,"adductors":0.5,"hamstrings":0.25},
  "Pendulum Squat": {"quads":1,"glutes":0.5,"adductors":0.25},
  "Reverse Hyperextension": {"glutes":1,"hamstrings":0.5,"lower_back":0.5},
  "Sled Push": {"quads":1,"glutes":0.5,"calves":0.5,"front_delt":0.25,"triceps":0.25,"abs":0.25},
  "Battle Ropes": {"front_delt":1,"side_delt":0.5,"forearms":0.5,"abs":0.5,"upper_back":0.25},
  "Stair Climber": {"quads":0.5,"glutes":0.5,"calves":0.5,"hamstrings":0.25},
  "Orbitrek": {"quads":0.5,"glutes":0.5,"hamstrings":0.25,"calves":0.25,"front_delt":0.25,"upper_back":0.25},
  "Ski Erg": {"lats":0.5,"triceps":0.5,"abs":0.5,"upper_back":0.25,"glutes":0.25,"front_delt":0.25},
  "Stability Ball Crunch": {"abs":1,"obliques":0.25},
  "Stability Ball Hamstring Curl": {"hamstrings":1,"glutes":0.5,"lower_back":0.25},
  "Slider Hamstring Curl": {"hamstrings":1,"glutes":0.5,"lower_back":0.25},
  "Slider Reverse Lunge": {"quads":1,"glutes":1,"adductors":0.25,"hamstrings":0.25},
};
/** Liczba linek obciążonych naraz (ćwiczenia na wyciągu) — do objętości na stacji (Q-024, po decyzji). */
export const CABLES: Readonly<Record<string, 1 | 2>> = {
  "Cable Fly": 2,
  "Wyciskanie na linkach (stojąc)": 2,
  "RDL (hantle/linki)": 2,
  "Seated Cable Row": 1,
  "Wiosłowanie na linkach (siedząc)": 2,
  "Lat Pulldown": 1,
  "Straight Arm Pulldown": 1,
  "Face Pull": 1,
  "Wyciskanie nad głowę (linki)": 2,
  "Cable Lateral Raise": 1,
  "Cable Curl": 1,
  "Triceps Pushdown": 1,
  "Cable Overhead Extension": 1,
  "Przysiad z pasem (linki)": 2,
  "Cable Kickback": 1,
  "Pallof Press": 1,
  "Cable Crunch": 1,
  "Cable Fly (low to high)": 2,
  "Cable Fly (high to low)": 2,
  "Incline Cable Fly": 2,
  "Single Arm Cable Fly": 1,
  "Single Arm Cable Chest Press": 1,
  "Single Arm Cable Row": 1,
  "Standing Cable Row": 1,
  "Bent Over Row (linki)": 2,
  "Single Arm Lat Pulldown": 1,
  "Shrugs (linki)": 2,
  "Cable Front Raise": 1,
  "Cable Reverse Fly": 2,
  "Cable Y Raise": 2,
  "Upright Row (linki)": 1,
  "External Rotation (linki)": 1,
  "Hammer Curl (linki)": 1,
  "Bayesian Curl": 1,
  "High Cable Curl": 2,
  "Cable Curl (dwie linki)": 2,
  "Single Arm Triceps Pushdown": 1,
  "Triceps Kickback (linki)": 1,
  "Single Leg RDL (linki)": 1,
  "Cable Squat": 2,
  "Split Squat (linki)": 2,
  "Standing Cable Leg Curl": 1,
  "Cable Pull Through": 1,
  "Cable Hip Abduction": 1,
  "Calf Raise (linki)": 2,
  "Cable Woodchop": 1,
  "Single Arm RDL (hantel/linka)": 1,
  "Cable Hip Adduction": 1,
};
/** Kolejne kroki dopisywania nowych ćwiczeń do danych użytkownika (State.libExtraStep — ostatni dopisany krok). */
export const CATALOG_ADDED_REVS = ["katalog-2026-10-04","katalog-2026-10-04b"] as const;
/** Ćwiczenia biblioteki dodane w katalogu (04.10.2026): [nazwa, partia, sprzęt, asysta gumą, miara, tryb liczenia, mięśnie główne, pomocnicze, krok dopisania]. */
export const CATALOG_LIB_EXTRA: readonly [string, string, string, boolean, string, string, string[], string[], string][] = [
  ["Incline Chest Fly (hantle)","klatka","hantle",false,"weight_reps","per_dumbbell",["klatka"],["barki"],"katalog-2026-10-04"],
  ["Decline Bench Press (hantle)","klatka","hantle",false,"weight_reps","per_dumbbell",["klatka"],["triceps"],"katalog-2026-10-04"],
  ["Floor Press (hantle)","klatka","hantle",false,"weight_reps","per_dumbbell",["klatka"],["triceps"],"katalog-2026-10-04"],
  ["Floor Press (sztanga)","klatka","sztanga",false,"weight_reps","total",["klatka"],["triceps"],"katalog-2026-10-04"],
  ["Squeeze Press (hantle)","klatka","hantle",false,"weight_reps","per_dumbbell",["klatka"],["triceps"],"katalog-2026-10-04"],
  ["Cable Fly (low to high)","klatka","linki",false,"weight_reps","total",["klatka"],["barki"],"katalog-2026-10-04"],
  ["Cable Fly (high to low)","klatka","linki",false,"weight_reps","total",["klatka"],[],"katalog-2026-10-04"],
  ["Incline Cable Fly","klatka","linki",false,"weight_reps","total",["klatka"],["barki"],"katalog-2026-10-04"],
  ["Single Arm Cable Fly","klatka","linki",false,"weight_reps","unilateral",["klatka"],[],"katalog-2026-10-04"],
  ["Single Arm Cable Chest Press","klatka","linki",false,"weight_reps","unilateral",["klatka"],["triceps"],"katalog-2026-10-04"],
  ["Svend Press","klatka","hantle",false,"weight_reps","total",["klatka"],[],"katalog-2026-10-04"],
  ["Decline Push Up","klatka","masa ciała",false,"weight_reps","total",["klatka"],["barki","triceps"],"katalog-2026-10-04"],
  ["Smith Machine Bench Press","klatka","maszyna",false,"weight_reps","total",["klatka"],["triceps"],"katalog-2026-10-04"],
  ["Smith Machine Incline Press","klatka","maszyna",false,"weight_reps","total",["klatka"],["barki","triceps"],"katalog-2026-10-04"],
  ["Pullover (hantel)","klatka","hantle",false,"weight_reps","total",["klatka","plecy"],[],"katalog-2026-10-04"],
  ["Single Arm Cable Row","plecy","linki",false,"weight_reps","unilateral",["plecy"],["biceps"],"katalog-2026-10-04"],
  ["Standing Cable Row","plecy","linki",false,"weight_reps","total",["plecy"],["biceps"],"katalog-2026-10-04"],
  ["Bent Over Row (linki)","plecy","linki",false,"weight_reps","total",["plecy"],["biceps"],"katalog-2026-10-04"],
  ["Meadows Row","plecy","sztanga",false,"weight_reps","unilateral",["plecy"],["biceps"],"katalog-2026-10-04"],
  ["Seal Row (sztanga)","plecy","sztanga",false,"weight_reps","total",["plecy"],["biceps"],"katalog-2026-10-04"],
  ["Rack Pull","plecy","sztanga",false,"weight_reps","total",["plecy"],["pośladki","dwugłowe"],"katalog-2026-10-04"],
  ["Single Arm Lat Pulldown","plecy","linki",false,"weight_reps","unilateral",["plecy"],["biceps"],"katalog-2026-10-04"],
  ["Renegade Row","plecy","hantle",false,"weight_reps","per_dumbbell",["plecy","core"],["biceps"],"katalog-2026-10-04"],
  ["Superman","plecy","masa ciała",false,"reps","total",["plecy"],["pośladki"],"katalog-2026-10-04"],
  ["Shrugs (linki)","plecy","linki",false,"weight_reps","total",["plecy"],[],"katalog-2026-10-04"],
  ["Dead Hang","plecy","masa ciała",false,"time","total",["przedramiona"],["plecy"],"katalog-2026-10-04"],
  ["Landmine Press","barki","sztanga",false,"weight_reps","unilateral",["barki"],["klatka","triceps"],"katalog-2026-10-04"],
  ["Single Arm Overhead Press (hantel)","barki","hantle",false,"weight_reps","unilateral",["barki"],["triceps"],"katalog-2026-10-04"],
  ["Cable Front Raise","barki","linki",false,"weight_reps","total",["barki"],[],"katalog-2026-10-04"],
  ["Cable Reverse Fly","barki","linki",false,"weight_reps","total",["barki"],["plecy"],"katalog-2026-10-04"],
  ["Y Raise (hantle)","barki","hantle",false,"weight_reps","per_dumbbell",["barki"],["plecy"],"katalog-2026-10-04"],
  ["Cable Y Raise","barki","linki",false,"weight_reps","total",["barki"],["plecy"],"katalog-2026-10-04"],
  ["Upright Row (linki)","barki","linki",false,"weight_reps","total",["barki"],["plecy"],"katalog-2026-10-04"],
  ["Upright Row (sztanga)","barki","sztanga",false,"weight_reps","total",["barki"],["plecy"],"katalog-2026-10-04"],
  ["Pike Push Up","barki","masa ciała",false,"weight_reps","total",["barki"],["triceps"],"katalog-2026-10-04"],
  ["Handstand Push Up","barki","masa ciała",false,"weight_reps","total",["barki"],["triceps"],"katalog-2026-10-04"],
  ["Kettlebell Press","barki","hantle",false,"weight_reps","unilateral",["barki"],["triceps"],"katalog-2026-10-04"],
  ["Smith Machine Shoulder Press","barki","maszyna",false,"weight_reps","total",["barki"],["triceps"],"katalog-2026-10-04"],
  ["External Rotation (linki)","barki","linki",false,"weight_reps","unilateral",["barki"],[],"katalog-2026-10-04"],
  ["External Rotation (hantel)","barki","hantle",false,"weight_reps","unilateral",["barki"],[],"katalog-2026-10-04"],
  ["Band Pull Apart","barki","inne",false,"reps","total",["barki"],["plecy"],"katalog-2026-10-04"],
  ["Hammer Curl (linki)","biceps","linki",false,"weight_reps","total",["biceps"],["przedramiona"],"katalog-2026-10-04"],
  ["Bayesian Curl","biceps","linki",false,"weight_reps","unilateral",["biceps"],[],"katalog-2026-10-04"],
  ["High Cable Curl","biceps","linki",false,"weight_reps","total",["biceps"],[],"katalog-2026-10-04"],
  ["Cable Curl (dwie linki)","biceps","linki",false,"weight_reps","total",["biceps"],[],"katalog-2026-10-04"],
  ["Preacher Curl (EZ)","biceps","sztanga",false,"weight_reps","total",["biceps"],[],"katalog-2026-10-04"],
  ["Reverse Curl","biceps","sztanga",false,"weight_reps","total",["biceps","przedramiona"],[],"katalog-2026-10-04"],
  ["Zottman Curl","biceps","hantle",false,"weight_reps","per_dumbbell",["biceps"],["przedramiona"],"katalog-2026-10-04"],
  ["Wrist Curl (hantle)","inne","hantle",false,"weight_reps","per_dumbbell",["przedramiona"],[],"katalog-2026-10-04"],
  ["Reverse Wrist Curl (hantle)","inne","hantle",false,"weight_reps","per_dumbbell",["przedramiona"],[],"katalog-2026-10-04"],
  ["Single Arm Triceps Pushdown","triceps","linki",false,"weight_reps","unilateral",["triceps"],[],"katalog-2026-10-04"],
  ["Triceps Kickback (linki)","triceps","linki",false,"weight_reps","unilateral",["triceps"],[],"katalog-2026-10-04"],
  ["Overhead Triceps Extension (EZ)","triceps","sztanga",false,"weight_reps","total",["triceps"],[],"katalog-2026-10-04"],
  ["Skullcrusher (sztanga)","triceps","sztanga",false,"weight_reps","total",["triceps"],[],"katalog-2026-10-04"],
  ["JM Press","triceps","sztanga",false,"weight_reps","total",["triceps"],["klatka"],"katalog-2026-10-04"],
  ["Tate Press","triceps","hantle",false,"weight_reps","per_dumbbell",["triceps"],[],"katalog-2026-10-04"],
  ["Single Leg RDL (hantel)","plecy","hantle",false,"weight_reps","unilateral",["dwugłowe","pośladki"],["plecy"],"katalog-2026-10-04"],
  ["Single Leg RDL (linki)","plecy","linki",false,"weight_reps","unilateral",["dwugłowe","pośladki"],["plecy"],"katalog-2026-10-04"],
  ["Cable Squat","nogi","linki",false,"weight_reps","total",["czworogłowe"],["pośladki"],"katalog-2026-10-04"],
  ["Single Leg Press","nogi","maszyna",false,"weight_reps","unilateral",["czworogłowe"],["pośladki"],"katalog-2026-10-04"],
  ["Split Squat","nogi","hantle",false,"weight_reps","per_dumbbell",["czworogłowe","pośladki"],[],"katalog-2026-10-04"],
  ["Split Squat (linki)","nogi","linki",false,"weight_reps","total",["czworogłowe","pośladki"],[],"katalog-2026-10-04"],
  ["Lateral Lunge","nogi","hantle",false,"weight_reps","per_dumbbell",["czworogłowe","pośladki"],[],"katalog-2026-10-04"],
  ["Curtsy Lunge","nogi","hantle",false,"weight_reps","per_dumbbell",["pośladki","czworogłowe"],[],"katalog-2026-10-04"],
  ["Cossack Squat","nogi","masa ciała",false,"weight_reps","total",["czworogłowe","pośladki"],[],"katalog-2026-10-04"],
  ["Bodyweight Squat","nogi","masa ciała",false,"reps","total",["czworogłowe"],["pośladki"],"katalog-2026-10-04"],
  ["Jump Squat","nogi","masa ciała",false,"reps","total",["czworogłowe"],["pośladki","łydki"],"katalog-2026-10-04"],
  ["Smith Machine Squat","nogi","maszyna",false,"weight_reps","total",["czworogłowe"],["pośladki"],"katalog-2026-10-04"],
  ["Zercher Squat","nogi","sztanga",false,"weight_reps","total",["czworogłowe"],["pośladki","core"],"katalog-2026-10-04"],
  ["Double Kettlebell Front Squat","nogi","hantle",false,"weight_reps","per_dumbbell",["czworogłowe"],["pośladki","core"],"katalog-2026-10-04"],
  ["Landmine Squat","nogi","sztanga",false,"weight_reps","total",["czworogłowe"],["pośladki"],"katalog-2026-10-04"],
  ["Sumo Squat (hantel)","nogi","hantle",false,"weight_reps","total",["czworogłowe","pośladki"],[],"katalog-2026-10-04"],
  ["Lunges (sztanga)","nogi","sztanga",false,"weight_reps","total",["czworogłowe","pośladki"],[],"katalog-2026-10-04"],
  ["Reverse Nordic","nogi","masa ciała",false,"weight_reps","total",["czworogłowe"],[],"katalog-2026-10-04"],
  ["Glute Ham Raise","nogi","masa ciała",true,"weight_reps","total",["dwugłowe"],["pośladki"],"katalog-2026-10-04"],
  ["Standing Cable Leg Curl","nogi","linki",false,"weight_reps","unilateral",["dwugłowe"],[],"katalog-2026-10-04"],
  ["Leg Curl (hantel)","nogi","hantle",false,"weight_reps","total",["dwugłowe"],[],"katalog-2026-10-04"],
  ["Cable Pull Through","pośladki","linki",false,"weight_reps","total",["pośladki"],["dwugłowe"],"katalog-2026-10-04"],
  ["Frog Pump","pośladki","masa ciała",false,"weight_reps","total",["pośladki"],[],"katalog-2026-10-04"],
  ["Single Leg Glute Bridge","pośladki","masa ciała",false,"weight_reps","total",["pośladki"],["dwugłowe"],"katalog-2026-10-04"],
  ["Single Leg Hip Thrust","pośladki","masa ciała",false,"weight_reps","total",["pośladki"],["dwugłowe"],"katalog-2026-10-04"],
  ["Glute Bridge (sztanga)","pośladki","sztanga",false,"weight_reps","total",["pośladki"],["dwugłowe"],"katalog-2026-10-04"],
  ["Smith Machine Hip Thrust","pośladki","maszyna",false,"weight_reps","total",["pośladki"],["dwugłowe"],"katalog-2026-10-04"],
  ["Sumo Deadlift (kettlebell)","pośladki","hantle",false,"weight_reps","total",["pośladki","czworogłowe"],["dwugłowe"],"katalog-2026-10-04"],
  ["Cable Hip Abduction","pośladki","linki",false,"weight_reps","unilateral",["pośladki"],[],"katalog-2026-10-04"],
  ["Lateral Band Walk","pośladki","inne",false,"reps","total",["pośladki"],[],"katalog-2026-10-04"],
  ["Fire Hydrant","pośladki","masa ciała",false,"reps","total",["pośladki"],[],"katalog-2026-10-04"],
  ["Donkey Kick","pośladki","masa ciała",false,"reps","total",["pośladki"],["dwugłowe"],"katalog-2026-10-04"],
  ["Clamshell","pośladki","masa ciała",false,"reps","total",["pośladki"],[],"katalog-2026-10-04"],
  ["Single Leg Calf Raise","łydki","hantle",false,"weight_reps","unilateral",["łydki"],[],"katalog-2026-10-04"],
  ["Seated Calf Raise (hantle)","łydki","hantle",false,"weight_reps","per_dumbbell",["łydki"],[],"katalog-2026-10-04"],
  ["Smith Machine Calf Raise","łydki","maszyna",false,"weight_reps","total",["łydki"],[],"katalog-2026-10-04"],
  ["Calf Raise (sztanga)","łydki","sztanga",false,"weight_reps","total",["łydki"],[],"katalog-2026-10-04"],
  ["Calf Raise (linki)","łydki","linki",false,"weight_reps","total",["łydki"],[],"katalog-2026-10-04"],
  ["Cable Woodchop","core","linki",false,"weight_reps","unilateral",["core"],[],"katalog-2026-10-04"],
  ["Landmine Rotation","core","sztanga",false,"weight_reps","total",["core"],["barki"],"katalog-2026-10-04"],
  ["Toes to Bar","core","masa ciała",false,"reps","total",["core"],[],"katalog-2026-10-04"],
  ["L-Sit","core","masa ciała",false,"time","total",["core"],[],"katalog-2026-10-04"],
  ["Plank Shoulder Taps","core","masa ciała",false,"reps","total",["core"],[],"katalog-2026-10-04"],
  ["Copenhagen Plank","core","masa ciała",false,"time","total",["przywodziciele"],["core"],"katalog-2026-10-04"],
  ["Decline Crunch","core","masa ciała",false,"weight_reps","total",["core"],[],"katalog-2026-10-04"],
  ["GHD Sit Up","core","masa ciała",false,"reps","total",["core"],[],"katalog-2026-10-04"],
  ["Sit Up","core","masa ciała",false,"weight_reps","total",["core"],[],"katalog-2026-10-04"],
  ["V-Up","core","masa ciała",false,"reps","total",["core"],[],"katalog-2026-10-04"],
  ["Bicycle Crunch","core","masa ciała",false,"reps","total",["core"],[],"katalog-2026-10-04"],
  ["Lying Leg Raise","core","masa ciała",false,"reps","total",["core"],[],"katalog-2026-10-04"],
  ["Dragon Flag","core","masa ciała",false,"reps","total",["core"],[],"katalog-2026-10-04"],
  ["Rollout (sztanga)","core","sztanga",false,"reps","total",["core"],[],"katalog-2026-10-04"],
  ["Side Bend (hantel)","core","hantle",false,"weight_reps","unilateral",["core"],[],"katalog-2026-10-04"],
  ["Kettlebell Windmill","core","hantle",false,"weight_reps","unilateral",["core"],["barki"],"katalog-2026-10-04"],
  ["Turkish Get Up","core","hantle",false,"weight_reps","unilateral",["core","barki"],["pośladki"],"katalog-2026-10-04"],
  ["Overhead Carry (hantle)","core","hantle",false,"weight_time","per_dumbbell",["core","barki"],[],"katalog-2026-10-04"],
  ["Double Kettlebell Front Rack Carry","core","hantle",false,"weight_time","per_dumbbell",["core"],["plecy"],"katalog-2026-10-04"],
  ["Farmer's Walk (trap bar)","core","sztanga",false,"weight_time","total",["przedramiona","plecy"],["core"],"katalog-2026-10-04"],
  ["Kettlebell Clean","inne","hantle",false,"weight_reps","unilateral",["pośladki","dwugłowe"],["plecy"],"katalog-2026-10-04"],
  ["Kettlebell Snatch","inne","hantle",false,"weight_reps","unilateral",["pośladki","barki"],["dwugłowe","plecy"],"katalog-2026-10-04"],
  ["Snatch (hantel)","inne","hantle",false,"weight_reps","unilateral",["pośladki","barki"],["dwugłowe","czworogłowe"],"katalog-2026-10-04"],
  ["Power Clean","inne","sztanga",false,"weight_reps","total",["pośladki","czworogłowe"],["plecy","dwugłowe"],"katalog-2026-10-04"],
  ["Thruster (hantle)","inne","hantle",false,"weight_reps","per_dumbbell",["czworogłowe","barki"],["pośladki","triceps"],"katalog-2026-10-04"],
  ["Wall Ball","cardio","inne",false,"reps","total",["czworogłowe"],["barki","pośladki"],"katalog-2026-10-04"],
  ["Jumping Jacks","cardio","masa ciała",false,"time","total",[],[],"katalog-2026-10-04"],
  ["High Knees","cardio","masa ciała",false,"time","total",[],[],"katalog-2026-10-04"],
  ["Broad Jump","cardio","masa ciała",false,"reps","total",["czworogłowe","pośladki"],[],"katalog-2026-10-04"],
  ["Single Arm RDL (hantel/linka)","plecy","hantle",false,"weight_reps","unilateral",["dwugłowe"],["pośladki","plecy"],"katalog-2026-10-04b"],
  ["Cable Hip Adduction","pośladki","linki",false,"weight_reps","unilateral",["przywodziciele"],[],"katalog-2026-10-04b"],
  ["Machine Row","plecy","maszyna",false,"weight_reps","total",["plecy"],["biceps"],"katalog-2026-10-04b"],
  ["Machine Pullover","plecy","maszyna",false,"weight_reps","total",["plecy"],[],"katalog-2026-10-04b"],
  ["Machine Crunch","core","maszyna",false,"weight_reps","total",["core"],[],"katalog-2026-10-04b"],
  ["Machine Biceps Curl","biceps","maszyna",false,"weight_reps","total",["biceps"],[],"katalog-2026-10-04b"],
  ["Machine Triceps Extension","triceps","maszyna",false,"weight_reps","total",["triceps"],[],"katalog-2026-10-04b"],
  ["Machine Lateral Raise","barki","maszyna",false,"weight_reps","total",["barki"],[],"katalog-2026-10-04b"],
  ["Machine Glute Kickback","pośladki","maszyna",false,"weight_reps","unilateral",["pośladki"],[],"katalog-2026-10-04b"],
  ["Machine Hip Thrust","pośladki","maszyna",false,"weight_reps","total",["pośladki"],[],"katalog-2026-10-04b"],
  ["Belt Squat Machine","nogi","maszyna",false,"weight_reps","total",["czworogłowe"],["pośladki"],"katalog-2026-10-04b"],
  ["Pendulum Squat","nogi","maszyna",false,"weight_reps","total",["czworogłowe"],["pośladki"],"katalog-2026-10-04b"],
  ["Reverse Hyperextension","pośladki","maszyna",false,"weight_reps","total",["pośladki"],["dwugłowe","plecy"],"katalog-2026-10-04b"],
  ["Sled Push","nogi","inne",false,"weight_time","total",["czworogłowe"],["pośladki","łydki"],"katalog-2026-10-04b"],
  ["Battle Ropes","cardio","inne",false,"time","total",["barki"],["przedramiona","core"],"katalog-2026-10-04b"],
  ["Stair Climber","cardio","maszyna",false,"time","total",[],[],"katalog-2026-10-04b"],
  ["Orbitrek","cardio","maszyna",false,"distance_time","total",[],[],"katalog-2026-10-04b"],
  ["Ski Erg","cardio","maszyna",false,"distance_time","total",[],[],"katalog-2026-10-04b"],
  ["Stability Ball Crunch","core","inne",false,"reps","total",["core"],[],"katalog-2026-10-04b"],
  ["Stability Ball Hamstring Curl","nogi","inne",false,"reps","total",["dwugłowe"],["pośladki"],"katalog-2026-10-04b"],
  ["Slider Hamstring Curl","nogi","inne",false,"reps","total",["dwugłowe"],["pośladki"],"katalog-2026-10-04b"],
  ["Slider Reverse Lunge","nogi","inne",false,"reps","unilateral",["czworogłowe","pośladki"],[],"katalog-2026-10-04b"],
];
