/* AUTOMATYCZNIE WYGENEROWANE przez scripts/equipment/gen.mjs z docs/research/equipment/catalog.json — nie edytować ręcznie.
 * Wymagania sprzętowe ćwiczeń biblioteki (P-003): requires = każda grupa musi być spełniona, w grupie wystarczy jedna możliwość. */
export type LoadSource = 'barbell' | 'dumbbell' | 'cable' | 'machine_stack' | 'bodyweight' | 'trap_bar' | 'ez_bar' | 'plate_loaded_machine' | 'kettlebell' | 'smith' | 'band' | 'none';
export type Pattern = 'h_push' | 'h_pull' | 'v_push' | 'v_pull' | 'squat' | 'hinge' | 'lunge_single_leg' | 'isolation' | 'core_flexion' | 'core_anti_ext' | 'core_anti_rot' | 'core_other' | 'carry' | 'cardio' | 'other';
export interface CatalogEntry { requires: string[][]; recommended: string[]; loadSource: LoadSource; pattern: Pattern; implements?: 1 | 2 }
/** Słownik możliwości użytych w katalogu (wymagane i zalecane), posortowany. */
export const CATALOG_CAPS: readonly string[] = ["ab_wheel","barbell","bench.decline","bench.flat","bench.incline","bench.uprights","box","cable.dual","cable.high","cable.low","cable.mid","cable.row_seat","calf_machine","cardio.bike","cardio.rower","cardio.treadmill","chest_press_machine","db","dip.bars","dip_belt","ez_bar","floor_mat","ghd","glute_ham_raise","hack_squat","hip_abductor_adductor","hyperext_bench","jump_rope","kb","landmine","lat_pulldown","leg_curl","leg_ext","leg_press","med_ball","outdoor","pec_deck","preacher_bench","pullup.bar","rack","rack.safeties","rings","shoulder_press_machine","smith","suspension","t_bar","trap_bar"];
export const CATALOG: Readonly<Record<string, CatalogEntry>> = {
  "Bench Press (sztanga)": {"requires":[["barbell"],["bench.flat"],["rack","bench.uprights"]],"recommended":["rack.safeties"],"loadSource":"barbell","pattern":"h_push"},
  "Bench Press (hantle)": {"requires":[["db"],["bench.flat"]],"recommended":[],"loadSource":"dumbbell","pattern":"h_push","implements":2},
  "Incline Bench Press (sztanga)": {"requires":[["barbell"],["bench.incline"],["rack","bench.uprights"]],"recommended":["rack.safeties"],"loadSource":"barbell","pattern":"h_push"},
  "Incline Bench Press (hantle)": {"requires":[["db"],["bench.incline"]],"recommended":[],"loadSource":"dumbbell","pattern":"h_push","implements":2},
  "Decline Bench Press": {"requires":[["barbell"],["bench.decline"],["rack","bench.uprights"]],"recommended":["rack.safeties"],"loadSource":"barbell","pattern":"h_push"},
  "Chest Fly (hantle)": {"requires":[["db"],["bench.flat"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Cable Fly": {"requires":[["cable.dual"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Pec Deck": {"requires":[["pec_deck"]],"recommended":[],"loadSource":"machine_stack","pattern":"isolation"},
  "Machine Chest Press": {"requires":[["chest_press_machine"]],"recommended":[],"loadSource":"machine_stack","pattern":"h_push"},
  "Wyciskanie na linkach (stojąc)": {"requires":[["cable.dual"],["cable.mid"]],"recommended":[],"loadSource":"cable","pattern":"h_push"},
  "Chest Dip": {"requires":[["dip.bars","rings"]],"recommended":[],"loadSource":"bodyweight","pattern":"v_push"},
  "Push Up": {"requires":[],"recommended":[],"loadSource":"bodyweight","pattern":"h_push"},
  "Incline Push Up": {"requires":[["bench.flat","box"]],"recommended":[],"loadSource":"bodyweight","pattern":"h_push"},
  "Diamond Push Up": {"requires":[],"recommended":[],"loadSource":"bodyweight","pattern":"h_push"},
  "Deadlift (sztanga)": {"requires":[["barbell"]],"recommended":[],"loadSource":"barbell","pattern":"hinge"},
  "Deadlift (hantle)": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"hinge","implements":2},
  "Sumo Deadlift": {"requires":[["barbell"]],"recommended":[],"loadSource":"barbell","pattern":"hinge"},
  "Trap Bar Deadlift": {"requires":[["trap_bar"]],"recommended":[],"loadSource":"trap_bar","pattern":"hinge"},
  "RDL (sztanga)": {"requires":[["barbell"]],"recommended":["rack"],"loadSource":"barbell","pattern":"hinge"},
  "RDL (hantle/linki)": {"requires":[["db","cable.low"]],"recommended":[],"loadSource":"dumbbell","pattern":"hinge","implements":2},
  "Bent Over Row (sztanga)": {"requires":[["barbell"]],"recommended":["rack"],"loadSource":"barbell","pattern":"h_pull"},
  "Bent Over Row (hantle)": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"h_pull","implements":2},
  "Pendlay Row": {"requires":[["barbell"]],"recommended":[],"loadSource":"barbell","pattern":"h_pull"},
  "One Arm Row (hantle)": {"requires":[["db"]],"recommended":["bench.flat"],"loadSource":"dumbbell","pattern":"h_pull","implements":1},
  "Chest Supported Row": {"requires":[["db"],["bench.incline"]],"recommended":[],"loadSource":"dumbbell","pattern":"h_pull","implements":2},
  "T-Bar Row": {"requires":[["t_bar","landmine"],["t_bar","barbell"]],"recommended":[],"loadSource":"barbell","pattern":"h_pull"},
  "Seated Cable Row": {"requires":[["cable.row_seat","cable.low"]],"recommended":[],"loadSource":"cable","pattern":"h_pull"},
  "Wiosłowanie na linkach (siedząc)": {"requires":[["cable.row_seat","cable.low"]],"recommended":[],"loadSource":"cable","pattern":"h_pull"},
  "Lat Pulldown": {"requires":[["lat_pulldown","cable.high"]],"recommended":[],"loadSource":"cable","pattern":"v_pull"},
  "Straight Arm Pulldown": {"requires":[["cable.high"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Chin Up": {"requires":[["pullup.bar","rings"]],"recommended":[],"loadSource":"bodyweight","pattern":"v_pull"},
  "Pull Up": {"requires":[["pullup.bar","rings"]],"recommended":[],"loadSource":"bodyweight","pattern":"v_pull"},
  "Neutral Grip Pull Up": {"requires":[["pullup.bar","rings"]],"recommended":[],"loadSource":"bodyweight","pattern":"v_pull"},
  "Inverted Row": {"requires":[["rack","smith","rings","suspension"],["barbell","smith","rings","suspension"]],"recommended":[],"loadSource":"bodyweight","pattern":"h_pull"},
  "Face Pull": {"requires":[["cable.high","cable.mid"]],"recommended":[],"loadSource":"cable","pattern":"h_pull"},
  "Back Extension": {"requires":[["hyperext_bench","ghd"]],"recommended":[],"loadSource":"bodyweight","pattern":"hinge"},
  "Shrugs (hantle)": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Shrugs (sztanga)": {"requires":[["barbell"]],"recommended":["rack"],"loadSource":"barbell","pattern":"isolation"},
  "Good Morning": {"requires":[["barbell"],["rack"]],"recommended":["rack.safeties"],"loadSource":"barbell","pattern":"hinge"},
  "Overhead Press (sztanga)": {"requires":[["barbell"]],"recommended":["rack"],"loadSource":"barbell","pattern":"v_push"},
  "Overhead Press (hantle)": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"v_push","implements":2},
  "Seated Shoulder Press (hantle)": {"requires":[["db"],["bench.flat","bench.incline","box"]],"recommended":["bench.incline"],"loadSource":"dumbbell","pattern":"v_push","implements":2},
  "Arnold Press": {"requires":[["db"]],"recommended":["bench.incline"],"loadSource":"dumbbell","pattern":"v_push","implements":2},
  "Push Press": {"requires":[["barbell"]],"recommended":["rack"],"loadSource":"barbell","pattern":"v_push"},
  "Machine Shoulder Press": {"requires":[["shoulder_press_machine"]],"recommended":[],"loadSource":"machine_stack","pattern":"v_push"},
  "Wyciskanie nad głowę (linki)": {"requires":[["cable.dual"],["cable.low"]],"recommended":[],"loadSource":"cable","pattern":"v_push"},
  "Lateral Raise (hantle)": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Cable Lateral Raise": {"requires":[["cable.low"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Front Raise": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Rear Delt Raise (hantle)": {"requires":[["db"]],"recommended":["bench.incline"],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Reverse Fly (hantle)": {"requires":[["db"]],"recommended":["bench.incline"],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Reverse Pec Deck": {"requires":[["pec_deck"]],"recommended":[],"loadSource":"machine_stack","pattern":"isolation"},
  "Upright Row": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Biceps Curl (hantle)": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Barbell Curl": {"requires":[["barbell"]],"recommended":[],"loadSource":"barbell","pattern":"isolation"},
  "EZ Bar Curl": {"requires":[["ez_bar"]],"recommended":[],"loadSource":"ez_bar","pattern":"isolation"},
  "Hammer Curl": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Incline Curl (hantle)": {"requires":[["db"],["bench.incline"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Concentration Curl (hantle)": {"requires":[["db"],["bench.flat","bench.incline","box"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":1},
  "Preacher Curl": {"requires":[["db"],["preacher_bench"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Spider Curl": {"requires":[["db"],["bench.incline"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Cable Curl": {"requires":[["cable.low"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Skullcrusher (hantle)": {"requires":[["db"],["bench.flat"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Skullcrusher (EZ)": {"requires":[["ez_bar"],["bench.flat"]],"recommended":[],"loadSource":"ez_bar","pattern":"isolation"},
  "Triceps Dips (ławka)": {"requires":[["bench.flat","box"]],"recommended":[],"loadSource":"bodyweight","pattern":"v_push"},
  "Triceps Pushdown": {"requires":[["cable.high"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Overhead Triceps Extension (hantel)": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"isolation","implements":1},
  "Cable Overhead Extension": {"requires":[["cable.high","cable.low"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Close Grip Bench Press": {"requires":[["barbell"],["bench.flat"],["rack","bench.uprights"]],"recommended":["rack.safeties"],"loadSource":"barbell","pattern":"h_push"},
  "Triceps Kickback": {"requires":[["db"]],"recommended":["bench.flat"],"loadSource":"dumbbell","pattern":"isolation","implements":1},
  "Back Squat": {"requires":[["barbell"],["rack"]],"recommended":["rack.safeties"],"loadSource":"barbell","pattern":"squat"},
  "Front Squat": {"requires":[["barbell"],["rack"]],"recommended":["rack.safeties"],"loadSource":"barbell","pattern":"squat"},
  "Goblet Squat": {"requires":[["db","kb"]],"recommended":[],"loadSource":"dumbbell","pattern":"squat","implements":1},
  "Przysiad z pasem (linki)": {"requires":[["cable.low"],["dip_belt"]],"recommended":[],"loadSource":"cable","pattern":"squat"},
  "Box Squat": {"requires":[["barbell"],["rack"],["bench.flat","box"]],"recommended":["rack.safeties"],"loadSource":"barbell","pattern":"squat"},
  "Hack Squat": {"requires":[["hack_squat"]],"recommended":[],"loadSource":"plate_loaded_machine","pattern":"squat"},
  "Leg Press": {"requires":[["leg_press"]],"recommended":[],"loadSource":"plate_loaded_machine","pattern":"squat"},
  "Bulgarian Split Squat (hantle)": {"requires":[["db"],["bench.flat","box"]],"recommended":[],"loadSource":"dumbbell","pattern":"lunge_single_leg","implements":2},
  "Lunges (hantle)": {"requires":[["db"]],"recommended":[],"loadSource":"dumbbell","pattern":"lunge_single_leg","implements":2},
  "Walking Lunges": {"requires":[],"recommended":["db"],"loadSource":"dumbbell","pattern":"lunge_single_leg","implements":2},
  "Reverse Lunge": {"requires":[],"recommended":["db"],"loadSource":"dumbbell","pattern":"lunge_single_leg","implements":2},
  "Step Up": {"requires":[["bench.flat","box"]],"recommended":["db"],"loadSource":"dumbbell","pattern":"lunge_single_leg","implements":2},
  "Leg Extension": {"requires":[["leg_ext"]],"recommended":[],"loadSource":"machine_stack","pattern":"isolation"},
  "Leg Curl": {"requires":[["leg_curl"]],"recommended":[],"loadSource":"machine_stack","pattern":"isolation"},
  "Lying Leg Curl": {"requires":[["leg_curl"]],"recommended":[],"loadSource":"machine_stack","pattern":"isolation"},
  "Nordic Curl": {"requires":[["ghd","glute_ham_raise","lat_pulldown","barbell"]],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"isolation"},
  "Pistol Squat": {"requires":[],"recommended":[],"loadSource":"bodyweight","pattern":"lunge_single_leg"},
  "Sissy Squat": {"requires":[],"recommended":[],"loadSource":"bodyweight","pattern":"isolation"},
  "Wall Sit": {"requires":[],"recommended":[],"loadSource":"bodyweight","pattern":"squat"},
  "Hip Thrust (sztanga)": {"requires":[["barbell"],["bench.flat","box"]],"recommended":[],"loadSource":"barbell","pattern":"hinge"},
  "Hip Thrust (hantel)": {"requires":[["db"],["bench.flat","box"]],"recommended":[],"loadSource":"dumbbell","pattern":"hinge","implements":1},
  "Glute Bridge": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"hinge"},
  "Cable Kickback": {"requires":[["cable.low"]],"recommended":[],"loadSource":"cable","pattern":"isolation"},
  "Hip Abduction": {"requires":[["hip_abductor_adductor"]],"recommended":[],"loadSource":"machine_stack","pattern":"isolation"},
  "Hip Adduction": {"requires":[["hip_abductor_adductor"]],"recommended":[],"loadSource":"machine_stack","pattern":"isolation"},
  "Kettlebell Swing": {"requires":[["kb","db"]],"recommended":[],"loadSource":"kettlebell","pattern":"hinge","implements":1},
  "Standing Calf Raise": {"requires":[["calf_machine"]],"recommended":[],"loadSource":"machine_stack","pattern":"isolation"},
  "Seated Calf Raise": {"requires":[["calf_machine"]],"recommended":[],"loadSource":"plate_loaded_machine","pattern":"isolation"},
  "Łydki na stopniu": {"requires":[],"recommended":["box","db"],"loadSource":"dumbbell","pattern":"isolation","implements":2},
  "Calf Press (leg press)": {"requires":[["leg_press"]],"recommended":[],"loadSource":"plate_loaded_machine","pattern":"isolation"},
  "Plank": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"core_anti_ext"},
  "Side Plank": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"core_other"},
  "Dead Bug": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"core_anti_ext"},
  "Bird Dog": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"core_anti_rot"},
  "Ab Wheel": {"requires":[["ab_wheel"]],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"core_anti_ext"},
  "Pallof Press": {"requires":[["cable.mid"]],"recommended":[],"loadSource":"cable","pattern":"core_anti_rot"},
  "Hanging Leg Raise": {"requires":[["pullup.bar","rings"]],"recommended":[],"loadSource":"bodyweight","pattern":"core_flexion"},
  "Hanging Knee Raise": {"requires":[["pullup.bar","rings","dip.bars"]],"recommended":[],"loadSource":"bodyweight","pattern":"core_flexion"},
  "Cable Crunch": {"requires":[["cable.high"]],"recommended":["floor_mat"],"loadSource":"cable","pattern":"core_flexion"},
  "Crunch": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"core_flexion"},
  "Reverse Crunch": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"core_flexion"},
  "Russian Twist": {"requires":[],"recommended":["db","floor_mat"],"loadSource":"dumbbell","pattern":"core_other","implements":1},
  "Hollow Hold": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"core_anti_ext"},
  "Farmer's Walk": {"requires":[["db","kb"]],"recommended":[],"loadSource":"dumbbell","pattern":"carry","implements":2},
  "Suitcase Carry": {"requires":[["db","kb"]],"recommended":[],"loadSource":"dumbbell","pattern":"carry","implements":1},
  "Mountain Climbers": {"requires":[],"recommended":["floor_mat"],"loadSource":"bodyweight","pattern":"cardio"},
  "Incline Walk (bieżnia)": {"requires":[["cardio.treadmill"]],"recommended":[],"loadSource":"none","pattern":"cardio"},
  "Bieg": {"requires":[],"recommended":[],"loadSource":"none","pattern":"cardio"},
  "Rower": {"requires":[["cardio.bike","outdoor"]],"recommended":[],"loadSource":"none","pattern":"cardio"},
  "Rowing Machine": {"requires":[["cardio.rower"]],"recommended":[],"loadSource":"none","pattern":"cardio"},
  "Assault Bike": {"requires":[["cardio.bike"]],"recommended":[],"loadSource":"none","pattern":"cardio"},
  "Skakanka": {"requires":[["jump_rope"]],"recommended":[],"loadSource":"none","pattern":"cardio"},
  "Burpees": {"requires":[],"recommended":[],"loadSource":"bodyweight","pattern":"cardio"},
  "Box Jump": {"requires":[["box"]],"recommended":[],"loadSource":"bodyweight","pattern":"other"},
  "Medicine Ball Slam": {"requires":[["med_ball"]],"recommended":[],"loadSource":"none","pattern":"other"},
};
