/* WYGENEROWANE — nie edytuj ręcznie. Źródło: scripts/equipment/catalog-1002-fields.json, skrypt: node scripts/equipment/legacy-fp.mjs (DAT2-02). */
/** Odciski pól ćwiczeń biblioteki z katalogu buildów 1001/1002: skrót seed.fpHash → nazwy (w tamtym katalogu) wszystkich ćwiczeń o tych polach. */
export const LEGACY_FP: Readonly<Record<string, readonly string[]>> = {
  "106ssqeot4o": ["Single Arm Cable Row"],
  "108prwqc5su": ["RDL (sztanga)"],
  "109ps8duz7s": ["Bodyweight Fly (rolling bars)"],
  "10bu10vp2q9": ["Slider Hamstring Curl"],
  "10er7kqpdi3": ["Triceps Pushdown","Reverse Grip Triceps Pushdown"],
  "10ieyx3joii": ["Medicine Ball Scoop Throw"],
  "10j1oklqmqn": ["Skullcrusher (EZ)"],
  "10ldd87ylxm": ["Close-Grip EZ-Bar Curl with Band"],
  "10mkxd4vg62": ["Car Drivers"],
  "10o0fbhxiy2": ["Chain Press"],
  "10o7fkvw1k5": ["Wyciskanie na linkach (stojąc)"],
  "10phbkty0se": ["Jump Squat","Alternate Leg Diagonal Bound","Double Leg Butt Kick","Split Jump","Star Jump","Side Standing Long Jump","Frog Hops"],
  "10y0so6i74": ["Barbell Curl","Close-Grip Standing Barbell Curl","Wide-Grip Standing Barbell Curl","Drag Curl"],
  "10yenb495ac": ["Good Morning"],
  "115azn3ivxp": ["One Arm Dumbbell Bench Press"],
  "115opfkgudp": ["Scapular Pull-Up"],
  "118ipehwxzj": ["Groiners","Hip Circles (Prone)","Inchworm","Iron Crosses (Stretch)","Pelvic Tilt Into Bridge","Windmills","World's Greatest Stretch"],
  "11b9lsfystf": ["Ankle Circles","Arm Circles","Crossover Reverse Lunge","Dynamic Back Stretch","Dynamic Chest Stretch","Elbow Circles","Front Leg Raises","Knee Circles","Shoulder Circles","Shoulder Raise","Side Leg Raises","Standing Hip Circles","Standing Pelvic Tilt","Wrist Circles"],
  "11f3a3smmqt": ["Burpees"],
  "11jcxazrxaz": ["Single-Arm Cable Crossover"],
  "11vkd8vb3s4": ["Bieg"],
  "11xgoiqo2tl": ["Wrist Roller"],
  "11yldyfd2qm": ["Upright Row (sztanga)"],
  "124to43f3d": ["Cable Fly"],
  "127o2d1k0q4": ["Sled Drag (Harness)"],
  "12c87n5u1c1": ["Wall Sit"],
  "12ll62djydz": ["Seal Row (sztanga)"],
  "12npkunvkd8": ["Open Palm Kettlebell Clean"],
  "130c7pojqid": ["Jumping Jacks","High Knees","Fast Skipping","Single-Cone Sprint Drill","Carioca Quick Step"],
  "134gh741zir": ["Decline Bench Press (hantle)"],
  "13a3uab9jrd": ["Lateral Cone Hops"],
  "13f0djsgdlp": ["Yoke Walk"],
  "13ghce8190y": ["Smith Machine Hip Raise"],
  "1495a8wgwwa": ["Kettlebell Pirate Ships"],
  "14kljkl2uwu": ["Suspended Fallout"],
  "14sasjehqol": ["Triceps Kickback (linki)"],
  "1536vvh54rv": ["Landmine Squat"],
  "15bc9nsf0bt": ["Floor Press with Chains"],
  "15dtbgzg26": ["Smith Machine Incline Press"],
  "15fln967kk7": ["Seated Side Lateral Raise"],
  "15xzugfl83c": ["Hip Extension with Bands"],
  "15zfek14e93": ["Box Jump"],
  "163pd9dwyv2": ["Stiff-Legged Barbell Deadlift"],
  "1657x8ajk1d": ["Standing Towel Triceps Extension"],
  "167aybdphb9": ["Ab Wheel"],
  "16bt4bl12ka": ["Chain Handle Extension"],
  "16ixdwn8wgp": ["Double Kettlebell Windmill"],
  "16kvufucc6l": ["Turkish Get Up"],
  "16lvf7yb7qv": ["Return Push from Stance"],
  "16mfatf0vkc": ["Single Dumbbell Raise"],
  "16mpze4bcqa": ["Incline Cable Chest Press"],
  "16v4fgf7d7i": ["Cable Russian Twists"],
  "172zli4rbzt": ["Reverse Curl"],
  "17583usifjm": ["Dumbbell Lying Pronation","Dumbbell Lying Supination"],
  "177ujcxxq7f": ["Push-Ups - Close Triceps Position"],
  "17ae05bb9bg": ["Kettlebell Sumo High Pull"],
  "17f191gh17i": ["Incline Push Up"],
  "17gjreurnb": ["Dumbbell Squat to a Bench"],
  "17iofigugc4": ["Pendlay Row"],
  "17p4p48u7p2": ["Thruster (hantle)"],
  "17smwxrfjq7": ["Snatch Balance","Heaving Snatch Balance"],
  "17stltcu42n": ["Band Skull Crusher"],
  "17u1nrnsx9x": ["Balance Board"],
  "17vjm5kaje8": ["Single-Leg Hop Progression","Single-Leg Lateral Hop"],
  "17wfan68fod": ["Weighted Bench Dip"],
  "183g1k6zp9o": ["Standing Leg Lift"],
  "188pe8f8wra": ["Standing Palms-Up Barbell Behind The Back Wrist Curl","Wrist Rotations with Straight Bar"],
  "18d8ysgpvmg": ["On-Your-Back Quad Stretch","Standing Elevated Quad Stretch"],
  "18g0to2lmuk": ["EZ Bar Curl","Close-Grip EZ Bar Curl"],
  "18hel5qt3tr": ["Chest Push from 3 Point Stance"],
  "18jy78zz4pn": ["Leg Curl (hantel)"],
  "18o2g9pvk91": ["Hammer Curl (linki)"],
  "18qfwi39yla": ["Shrugs (linki)"],
  "18v7r8n56gw": ["Prone Manual Hamstring"],
  "18vng4dv8r9": ["Snatch Pull"],
  "190e4y5sexn": ["Sledgehammer Swings"],
  "1955luen21l": ["Barbell Hack Squat"],
  "1968oscfuqp": ["Cable Reverse Fly"],
  "196jetrcj3m": ["Standing Low-Pulley One-Arm Triceps Extension"],
  "198vf2ebyvk": ["Body-Up"],
  "19bvzvl1caj": ["Seated Good Mornings"],
  "19es8dkry7q": ["Kettlebell One-Legged Deadlift"],
  "19mpepilx7w": ["Axle Deadlift"],
  "19olcc6it5g": ["Reverse Band Deadlift"],
  "19wm6ak8u9x": ["Dip Machine"],
  "1a09d4z9f11": ["Bulgarian Split Squat (hantle)"],
  "1a2mydasxac": ["Box Squat"],
  "1a3m1pz4fhm": ["Weighted Jump Squat"],
  "1a9kfs4s71i": ["Machine Chest Press"],
  "1aew7sj4imc": ["Jerk Balance"],
  "1anxxbrop6p": ["Leg Press","Narrow Stance Leg Press"],
  "1au6ec2kmbh": ["Body Tricep Press"],
  "1b13lwqnw40": ["Reverse Nordic"],
  "1b3zoekq6g5": ["Dumbbell Scaption","Cuban Press"],
  "1b4ekymu78o": ["Overhead Triceps Extension (hantel)"],
  "1b8bt1ms20v": ["Clean"],
  "1bd4k44cgvm": ["Arnold Press"],
  "1bjhhdsathb": ["Machine Hip Thrust"],
  "1bkykt9i7bp": ["Weighted Ball Hyperextension"],
  "1brs3hhenlm": ["External Rotation with Band","Internal Rotation with Band"],
  "1bw8k76tktu": ["Lat Pulldown","Close-Grip Front Lat Pulldown","Underhand Cable Pulldowns","V-Bar Pulldown"],
  "1bzfx7vqwsc": ["Inverted Row"],
  "1c6l96uuc85": ["Band Good Morning"],
  "1c7pik0j5fo": ["Cable Fly (low to high)"],
  "1cfp1ikwjah": ["Bench Press (sztanga)"],
  "1cmqjc0qfzl": ["Suspended Split Squat"],
  "1coicqhv739": ["Spell Caster"],
  "1cprj8kfrhr": ["Wide-Grip Pulldown Behind The Neck"],
  "1cptx4wbm5o": ["Supine Chest Throw"],
  "1cwhexy3b91": ["Cable Curl (dwie linki)"],
  "1cykzi3okiz": ["Iron Cross"],
  "1d776jwt4lw": ["Pullover (hantel)"],
  "1dd8l512dyb": ["Cable Deadlift"],
  "1di2oyo931r": ["Split Squat (linki)"],
  "1dodhnlsvum": ["Dumbbell Incline Shoulder Raise"],
  "1drfh5xbdnt": ["High Cable Curl"],
  "1du8ael7z6d": ["Overhead Press (hantle)","Standing Palms-In Dumbbell Press"],
  "1dvbxksrio4": ["Medicine Ball Chest Pass"],
  "1e8ca52pujc": ["Deadlift with Chains"],
  "1e90hz8eez8": ["Sumo Deadlift (kettlebell)"],
  "1ef9ydj2bnv": ["Chest And Front Of Shoulder Stretch","Standing Hamstring and Calf Stretch"],
  "1efkm0z6rcw": ["Narrow Stance Squats"],
  "1ehan9f4zv": ["Seated Calf Raise (hantle)"],
  "1f4t4a1ja03": ["Prone Flutter Kicks"],
  "1f6bircutdx": ["Reverse Flyes With External Rotation"],
  "1fgn7cu5122": ["Kneeling Cable Crunch With Alternating Oblique Twists"],
  "1fozxcfj222": ["Bent-Arm Barbell Pullover"],
  "1ftbfs84xrw": ["Hamstring Stretch","IT Band and Glute Stretch","Intermediate Groin Stretch","Intermediate Hip Flexor and Quad Stretch","Peroneals Stretch","Posterior Tibialis Stretch","Seated Hamstring and Calf Stretch"],
  "1fvdetuewb5": ["Pyramid"],
  "1fzerzw7hwg": ["Clean and Jerk"],
  "1fzjsgc5iwk": ["Machine Shoulder Press"],
  "1grg48q7l1u": ["Single Arm Cable Chest Press"],
  "1gsb10ypqo9": ["Double Kettlebell Snatch"],
  "1gus02pomfn": ["One Arm Floor Press"],
  "1gvv98cosud": ["Cable Fly (high to low)"],
  "1h1hbkp79ui": ["Bench Press with Chains"],
  "1h3kwhqkpge": ["Push-Ups With Feet On A Stability Ball"],
  "1hhkhnerh1": ["Power Clean"],
  "1hk2omuh9bb": ["Shrugs (sztanga)"],
  "1hmz72n6ofp": ["Seated Bent-Over Two-Arm Dumbbell Triceps Extension"],
  "1hthoqlwk84": ["Smith Machine Hip Thrust"],
  "1i93imvu5l5": ["Machine Row"],
  "1i9bm8rrz9u": ["Leg Extension"],
  "1ifhufftzs5": ["Single Leg Push-Off"],
  "1iznqcwv91d": ["Bench Press (hantle)","Dumbbell Bench Press with Neutral Grip"],
  "1izry5h7cs4": ["Rack Pull with Bands"],
  "1j8mcaih6qs": ["Kettlebell Seated Press"],
  "1jf4p5f7tz5": ["Kneeling Arm Drill"],
  "1jtaalw6ec8": ["Treadmill Walking"],
  "1jtvfexua9d": ["Supine One-Arm Overhead Throw"],
  "1jv213041mk": ["Sumo Squat (hantel)"],
  "1jv8vjcuzes": ["Zottman Preacher Curl"],
  "1k1ppkbxzt1": ["Hip Thrust (hantel)"],
  "1k2le4yql7p": ["One-Arm Kettlebell Row"],
  "1k7qboijb98": ["Skullcrusher (hantle)","Tate Press","Dumbbell Tricep Extension - Pronated Grip"],
  "1k8bue0wr9m": ["Bird Dog","Plank Shoulder Taps"],
  "1kajrockhky": ["Lateral Raise (hantle)","Front Raise","Alternating Deltoid Raise","Side Laterals to Front Raise","Standing Dumbbell Straight-Arm Front Delt Raise Above Head"],
  "1kerecwc1va": ["Trap Bar Deadlift"],
  "1kmmeto8kif": ["Box Squat with Chains"],
  "1kskow3a1da": ["Lying T-Bar Row"],
  "1l6u631n6s5": ["Full Range-Of-Motion Lat Pulldown"],
  "1l8fgfgqbs": ["Bent Over Row (linki)"],
  "1lh3k8hkq5d": ["Bent Over Row (hantle)","Bent Over Two-Dumbbell Row With Palms In"],
  "1lixl8ppgx5": ["One-Arm Kettlebell Push Press","One-Arm Kettlebell Jerk","One-Arm Kettlebell Split Jerk"],
  "1lt1ffe4wfa": ["Renegade Row"],
  "1lwm0gkav1t": ["Hip Thrust (sztanga)"],
  "1lwzhy1evvy": ["London Bridges"],
  "1lxdjnoer9w": ["Lateral Raise - With Bands"],
  "1m1m0mqv9bh": ["Leverage High Row"],
  "1m3f3k49wwn": ["Landmine Press"],
  "1m7bhsdb66b": ["Jerk Dip Squat"],
  "1m8ejnuj918": ["Cable Internal Rotation"],
  "1mdhtti9ayv": ["Lying Cable Curl"],
  "1mgj6is7atj": ["One-Arm Kettlebell Swings"],
  "1mq26ay4vzv": ["Kneeling High Pulley Row"],
  "1mv74s3llrb": ["Straight Raises on Incline Bench"],
  "1n0xhcb1m3f": ["Donkey Kick"],
  "1n166appgbt": ["Pendulum Squat"],
  "1n75eoilv44": ["Overhead Press (sztanga)","Standing Bradford Press"],
  "1ngd4doynza": ["Kettlebell Clean"],
  "1nsp4rwc89l": ["Smith Machine Hang Power Clean"],
  "1nyjhihaq7t": ["Around The Worlds"],
  "1nz6es0l13y": ["Single Arm Cable Fly"],
  "1o7w95j30fr": ["Smith Machine Single-Leg Split Squat"],
  "1o8mvi86cgy": ["Barbell Guillotine Bench Press","Wide-Grip Barbell Bench Press"],
  "1p0e82in6kl": ["Decline EZ Bar Triceps Extension"],
  "1p3w3bpvi85": ["Lying High Bench Barbell Curl"],
  "1p5le77yhkh": ["Decline Close-Grip Bench To Skull Crusher"],
  "1pb0n5k6gtw": ["Clean Deadlift"],
  "1pna0gs1zs2": ["Standing Bent-Over Two-Arm Dumbbell Triceps Extension"],
  "1px966hvw0f": ["Clean Pull"],
  "1q0kjhi3hw3": ["Clean from Blocks","Snatch from Blocks"],
  "1q2wvlp74xa": ["Incline Push-Up Reverse Grip"],
  "1q3ghc92lwy": ["Stair Climber"],
  "1qbjzc5jiov": ["Stiff-Legged Dumbbell Deadlift"],
  "1qc6hhqx34u": ["Dumbbell Seated One-Leg Calf Raise"],
  "1qfcwlxposd": ["Supine Two-Arm Overhead Throw"],
  "1qli22957ou": ["Sumo Deadlift with Chains"],
  "1qorh8ogi0r": ["Stomach Vacuum"],
  "1qov83zxzs6": ["Rack Delivery"],
  "1qrag731t1e": ["Hyperextensions With No Hyperextension Bench"],
  "1qslupt43uj": ["Calf Raises with Bands"],
  "1qu67gcyrbj": ["Chest Fly (hantle)"],
  "1qu9lfok8td": ["Seated Bent-Over Rear Delt Raise"],
  "1quyuopmtra": ["Smith Machine Calf Raise","Smith Machine Reverse Calf Raises"],
  "1r8efsd4xo": ["Incline Bench Press (hantle)","Hammer Grip Incline DB Bench Press"],
  "1r9j7kvcsdj": ["Dumbbell Seated Box Jump"],
  "1rc9hsnc3cq": ["Chest Stretch on Stability Ball","Hug A Ball"],
  "1rff4xdiu0w": ["Plate Twist"],
  "1ryuld0mhqc": ["Farmer's Walk"],
  "1sgj1ddqd4b": ["One-Arm Kettlebell Split Snatch"],
  "1sm67k2ohmb": ["Biceps Curl (hantle)","Hammer Curl","Standing Inner-Biceps Curl"],
  "1sosqm2oow5": ["90/90 Hamstring","Adductor/Groin","All Fours Quad Stretch","Ankle On The Knee","Behind Head Chest Stretch","Cat Stretch","Child's Pose","Chin To Chest Stretch","Dancer's Stretch","Groin and Back Stretch","Hug Knees To Chest","Knee Across The Body","Kneeling Forearm Stretch","Kneeling Hip Flexor","Looking At Ceiling","Lying Bent Leg Groin","Lying Crossover","Lying Glute","Lying Hamstring","Lying Prone Quadriceps","On Your Side Quad Stretch","One Half Locust","One Knee To Chest","Overhead Lat","Overhead Triceps","Runner's Stretch","Seated Biceps","Seated Calf Stretch","Seated Floor Hamstring Stretch","Seated Front Deltoid","Seated Glute","Seated Hamstring","Seated Overhead Stretch","Side-Lying Floor Stretch","Side Lying Groin Stretch","The Straddle","Upper Back-Leg Grab"],
  "1srwuj5pb4r": ["Kipping Muscle Up","Muscle Up"],
  "1swp6xpyv4j": ["Kneeling Squat"],
  "1t3qiltjaxv": ["Hip Flexion with Band"],
  "1th1ue3uh6j": ["Reverse Cable Curl"],
  "1thjc67g8qx": ["Backward Drag"],
  "1tjv91l2xry": ["Side Plank"],
  "1to2ht2l1ez": ["Lower Back Curl"],
  "1twc4etcbmb": ["Lateral Bound"],
  "1tz17ryl5ny": ["Decline Crunch","Decline Oblique Crunch"],
  "1ud48a9juto": ["Glute Bridge (sztanga)"],
  "1ug9l1k54ye": ["Single-Arm Linear Jammer"],
  "1ugald6tp9n": ["Suspended Push-Up"],
  "1uiu5ui665i": ["Farmer's Walk (Farmers Handles)"],
  "1uwfre46vzc": ["Plate Pinch"],
  "1uxa4jtp3k6": ["Curtsy Lunge"],
  "1v1gcux7n6": ["Kettlebell Halo with Overhead Extension"],
  "1v2y6l0akwy": ["Incline Walk (bieżnia)"],
  "1vhaw7tksr2": ["Standing Leg Curl"],
  "1vlzb5wljmj": ["Double Kettlebell Front Squat"],
  "1vq53ehb1p0": ["Medicine Ball Slam"],
  "1vs3ra5myiz": ["Bent Over Low-Pulley Side Lateral"],
  "1w6aetoecnt": ["Clock Push-Up","Isometric Wipers"],
  "1wgoc8e1f93": ["Triceps Kickback"],
  "1wr0glebj7g": ["Band Chest Fly"],
  "1wzv6ttjphk": ["Rollout (sztanga)","Barbell Ab Rollout"],
  "1x2p7jmae28": ["Calf Raise On A Dumbbell"],
  "1x73onno86l": ["Power Stairs"],
  "1x85r1x5wvz": ["Kneeling Cable Triceps Extension"],
  "1x97rv05qdh": ["Keg Load"],
  "1xdt3sogd1n": ["Reverse Band Power Squat","Squat with Bands"],
  "1xgmzky5iaw": ["Backward Medicine Ball Throw"],
  "1xmkdp9bh07": ["Pike Push Up"],
  "1xn9hgndx1g": ["Assault Bike","Recumbent Bike"],
  "1y62onv869u": ["Wrist Curl (hantle)","Reverse Wrist Curl (hantle)"],
  "1y9dduw34a8": ["Single Leg Butt Kick"],
  "1yb8lp57mgt": ["Calf Raise (linki)"],
  "1yloab7df9x": ["Standing Overhead Barbell Triceps Extension"],
  "1yls75bt966": ["Push-Up Wide"],
  "1ynui5iwdf0": ["Close-Grip Dumbbell Press"],
  "1yrtqzqpf0b": ["Side Hop-Sprint"],
  "1ytgoipzk5o": ["Seated Bent-Over One-Arm Dumbbell Triceps Extension"],
  "1z13xk8rqd": ["Rope Climb"],
  "1zgizj9z4x6": ["Seated Head Harness Neck Resistance"],
  "1zmcw9ub9wm": ["Seated Dumbbell Curl","Seated Dumbbell Inner Biceps Curl"],
  "1zp7tou9n7i": ["Double Kettlebell Front Rack Carry"],
  "1zr78saq62": ["Reverse Plate Curls"],
  "20czs5rkbze": ["Stability Ball Hamstring Curl"],
  "20ti6syvb4t": ["Hang Clean","Hang Clean Below the Knees","Split Clean","Barbell Snatch"],
  "20vz6rfbop": ["Upright Row (linki)"],
  "2122564lrj8": ["External Rotation (hantel)"],
  "212spukd7q2": ["Plyo Kettlebell Push-Ups"],
  "213sahfxkan": ["Calf Press (leg press)"],
  "216kn6jka0m": ["Superman"],
  "21c5qyc3ngz": ["Incline Chest Fly (hantle)","Incline Dumbbell Fly With A Twist"],
  "21dbee4t6ho": ["Band Good Morning (Pull Through)"],
  "22oguctlo76": ["Standing Cable Row"],
  "22ra2y5ua5p": ["Kneeling Chest Push (single response)"],
  "22tqr44kwih": ["Box Squat with Bands","Reverse Band Box Squat"],
  "23dk6py0jag": ["Decline Dumbbell Fly"],
  "23skxz116xh": ["Kettlebell Swing"],
  "23tzq10lz96": ["Lunges (sztanga)"],
  "23wd0iksn45": ["Rickshaw Carry"],
  "242qitqtxyz": ["Dragon Flag"],
  "247go3hzzit": ["Wyciskanie nad głowę (linki)"],
  "24txbjge6zx": ["Round The World Shoulder Stretch"],
  "24wqv225o1b": ["External Rotation (linki)"],
  "24x5uw9erec": ["Lateral Band Walk","Monster Walk"],
  "250loho7wcf": ["Upright Row"],
  "252slgw9ksd": ["Seated Barbell Military Press","Seated Bradford/Rocky Press"],
  "253acff25nq": ["Back Extension"],
  "25grkxhfkwd": ["V-Up","Bicycle Crunch","Bottoms Up","Butt-Ups","Cocoons","Cross-Body Crunch","Janda Sit-Up","Tuck Crunch","Scissor Kick","Toe Touchers"],
  "25u57nx9urd": ["Standing One-Arm Cable Curl"],
  "25udphah8op": ["Bent Press"],
  "25ufylymoop": ["Alternating Kettlebell Floor Press"],
  "25ylizd7smm": ["Drop Push","Incline Push-Up Depth Jump"],
  "263non4z51c": ["Barbell Preacher Curl"],
  "263v5s8g7jz": ["Face Pull"],
  "26elhhcjv4": ["Machine Pullover"],
  "26galgx0448": ["Straight Arm Pulldown"],
  "26i6oymb99f": ["Conan's Wheel"],
  "26lw8t8alq2": ["Cable Pull Through"],
  "26rkywvyj3c": ["Glute Bridge","Single Leg Glute Bridge"],
  "26ty06yt8hs": ["Wide Stance Barbell Squat"],
  "26xoyjz85lx": ["Power Snatch from Blocks"],
  "26yz5yrzp7i": ["Wall Ball"],
  "270rikzfny8": ["Back Squat"],
  "2710sofrvzk": ["Smith Machine Close-Grip Bench Press"],
  "27f94ldawgk": ["Kettlebell Snatch"],
  "27gf3gde1vl": ["Single Arm Triceps Pushdown","Cable One Arm Triceps Extension"],
  "27y4w6jnapl": ["Smith Machine Behind the Back Shrug"],
  "285a60deepv": ["Extended Range One-Arm Kettlebell Floor Press","One-Arm Kettlebell Floor Press"],
  "28c6t6kf8tu": ["Goblet Squat"],
  "28iv3lcjpsi": ["Overhead Squat"],
  "28obhxsi9ea": ["Bench Jump","Bench Sprint"],
  "28p2110vz4t": ["One-Arm Medicine Ball Slam"],
  "28pwfohd7en": ["Front Plate Raise"],
  "28zoqi091up": ["Slider Reverse Lunge"],
  "2936b3y081j": ["Kettlebell Pistol Squat"],
  "293dtqiptkm": ["Close-Grip Push-Up off of a Dumbbell"],
  "293g9eqcth0": ["One-Arm Overhead Kettlebell Squat"],
  "29dro62mnx4": ["Seated Band Hamstring Curl"],
  "29eggz6orn2": ["L-Sit"],
  "29fffyr5s0f": ["Calf Raise (sztanga)","Rocking Standing Calf Raise"],
  "29i73kgen6g": ["Zottman Curl","Cross Body Hammer Curl"],
  "29kshuybv3g": ["Knee Tuck Jump"],
  "29l2f254mcz": ["Anti-Gravity Press"],
  "29ltnp1r4k1": ["Cable Curl"],
  "2a139qqr2r8": ["Circus Bell"],
  "2aabpparzbc": ["Snatch Deadlift"],
  "2aerd7fopy6": ["Mixed Grip Chin","Side To Side Chins"],
  "2af22nftmp1": ["Incline Barbell Triceps Extension"],
  "2akh6764ey6": ["Machine Glute Kickback"],
  "2akn4ip6kay": ["Barbell Side Split Squat","Barbell Walking Lunge"],
  "2al91u236ro": ["Mountain Climbers"],
  "2b09d3y09ws": ["Close-Grip EZ-Bar Press"],
  "2b2bmjsvr53": ["Sled Push"],
  "2b67xa7iens": ["Floor Press (sztanga)"],
  "2bao67j64kt": ["Bent Over Row (sztanga)","Reverse Grip Bent-Over Rows"],
  "2bcyasqy1gp": ["Cable Reverse Crunch"],
  "2bh7jvppivw": ["Hang Snatch","Split Snatch"],
  "2bi110sorva": ["Sissy Squat"],
  "2biaeh0t8wd": ["Muscle Snatch"],
  "2blgv1nzbpr": ["Seated Barbell Twist"],
  "2c4h49cfy1n": ["Dumbbell One-Arm Triceps Extension"],
  "2cbnc26bn5c": ["Close Grip Bench Press","JM Press"],
  "2cgtj87laj8": ["Weighted Ball Side Bend"],
  "2ct7bgfldij": ["Leg Curl","Lying Leg Curl"],
  "2cylo55k57t": ["Lying Supine Dumbbell Curl"],
  "2dabgyrts8s": ["Alternate Heel Touchers","Oblique Crunches - On The Floor","Side Jackknife"],
  "2ddsia53l1q": ["Rack Pull"],
  "2dk2okl8izp": ["Toes to Bar"],
  "2dv9tm51tdm": ["Barbell Rear Delt Row"],
  "2dvhgazrc89": ["Concentration Curl (hantle)"],
  "2e4kh34q1kz": ["Push Press - Behind the Neck"],
  "2e5drcn5ra8": ["Middle Back Shrug"],
  "2e8ixw7xlul": ["Copenhagen Plank"],
  "2e9qosb5uke": ["Leverage Deadlift"],
  "2eb35o8kzvj": ["Kneeling Single-Arm High Pulley Row"],
  "2edyhedsxq3": ["Pec Deck"],
  "2em8k9ap6oh": ["Broad Jump"],
  "2ezx5fzncqn": ["Band Bench Press"],
  "2f3wn9omnhl": ["Plank","Hollow Hold"],
  "2f53l04ab4k": ["One Handed Hang"],
  "2f9b30gouih": ["Crucifix"],
  "2fa2rnkhuga": ["Incline Bench Press (sztanga)"],
  "2flniasdspn": ["Hack Squat","Narrow Stance Hack Squat"],
  "2foembe0mqp": ["Glute Ham Raise"],
  "2fr2sqkot1z": ["Seated Calf Raise","Donkey Calf Raises"],
  "2fr9ajugqdm": ["Sumo Deadlift with Bands"],
  "2frqru0vovm": ["Chin Up","Pull Up","Neutral Grip Pull Up","Gironda Sternum Chins"],
  "2g0fcv884da": ["Barbell Step Up","One Leg Barbell Squat"],
  "2g1rqengsho": ["Side Bend (hantel)"],
  "2g2ssjlurng": ["Seated Close-Grip Concentration Barbell Curl"],
  "2g9jzq8oyck": ["Standing Rope Crunch"],
  "2g9rx4ymenn": ["One-Arm Side Laterals"],
  "2ghlutgqq7q": ["Seated Cable Shoulder Press"],
  "2gn98lm1d6a": ["Cable Overhead Extension"],
  "2gpiiloyjz": ["Russian Twist"],
  "2iixxpmnad": ["RDL (hantle/linki)"],
  "2qsaf01rv5": ["Smith Machine Pistol Squat"],
  "2z98tjq1x": ["Suspended Reverse Crunch"],
  "34110u7ncg": ["Linear Acceleration Wall Drill"],
  "3gfow6wb97": ["Smith Machine Upright Row"],
  "3irsu18qm9": ["Dead Hang"],
  "3m7nmf724x": ["Adductor-SMR","Brachialis-SMR","Calves-SMR","Hamstring-SMR","Iliotibial Tract-SMR","Latissimus Dorsi-SMR","Lower Back-SMR","Peroneals-SMR","Piriformis-SMR","Quadriceps-SMR","Rhomboids-SMR","Anterior Tibialis-SMR","Foot-SMR","Neck-SMR"],
  "3p9k1tzdnq": ["Sled Overhead Backward Walk"],
  "3qarb5npf2": ["Decline Dumbbell Triceps Extension"],
  "3xylpbw0tt": ["One Arm Chin-Up"],
  "4gfy5jmv7n": ["Sumo Deadlift"],
  "4j84gy86gc": ["Plyo Push-Up"],
  "4mo6kb9fx9": ["Pallof Press With Rotation"],
  "4njpliwvre": ["Hip Adduction"],
  "4wfdblkzet": ["Dumbbell Lying One-Arm Rear Lateral Raise"],
  "54aa7qvorp": ["Crunch","Reverse Crunch","Sit Up","3/4 Sit-Up","Crunch - Hands Overhead","Frog Sit-Ups"],
  "54f0ayb9ew": ["Seated Cable Row","Wiosłowanie na linkach (siedząc)"],
  "55fssup0ty": ["Standing Front Barbell Raise Over Head"],
  "56siq6n4ys": ["Rower"],
  "5agtnrqnzw": ["Deadlift (sztanga)","Deficit Deadlift"],
  "5m7pxy6rlf": ["Lying Close-Grip Barbell Triceps Extension Behind The Head"],
  "5p72vnfj4a": ["Sled Forward Drag with Press"],
  "5uinm5ideu": ["Wide-Grip Decline Barbell Pullover"],
  "65hxuaf2j6": ["Preacher Curl"],
  "65rk6dfucy": ["Smith Machine Stiff-Legged Deadlift"],
  "68f71d7oyy": ["Deadlift with Bands"],
  "69uvwf1pu9": ["Dumbbell Squat"],
  "6al2l1nx4k": ["Incline Push-Up Wide"],
  "6cjbuqyjvv": ["Clean and Press"],
  "6ll29vvz1r": ["Landmine Linear Jammer"],
  "6md4yfzz2d": ["Reverse Pec Deck"],
  "6q020qre2w": ["Calf-Machine Shoulder Shrug"],
  "6q5xt8ib0j": ["Dip Belt Squat"],
  "6qad6v72bn": ["Standing One-Arm Dumbbell Curl Over Incline Bench"],
  "6wrttfbsuk": ["Band Pull Apart"],
  "71u9ravl9y": ["Atlas Stone Trainer"],
  "79jv0k458k": ["Push Press"],
  "7c20tljpr8": ["Dead Bug"],
  "7pan97s3mc": ["Shoulder Press - With Bands"],
  "7ribzdt5wc": ["Otis-Up"],
  "7s3eb2urhz": ["Reverse Band Bench Press"],
  "7vogghrmg9": ["Front Incline Dumbbell Raise"],
  "80qf716ebb": ["Cable Seated Crunch"],
  "81v4m9m8a9": ["Kettlebell Halo"],
  "896tjvdh54": ["Kettlebell Figure 8"],
  "8ftxc9aera": ["Cable Squat"],
  "8kxzyc5p4r": ["Atlas Stones"],
  "8lqxw92bd5": ["Battle Ropes"],
  "8q9ek0x5si": ["Push Up"],
  "8tsaumglwa": ["Incline Cable Fly"],
  "8ujwqnvsz2": ["Flat Bench Cable Fly"],
  "9eqfvd8fwq": ["Lunge Sprint"],
  "9hyaeyb4r": ["Sled Row"],
  "9mxdgsg3gl": ["Barbell Incline Shoulder Raise"],
  "9snwxpvpjf": ["Barbell Curls Lying Against An Incline"],
  "9ssvhqx1fw": ["Standing Concentration Curl"],
  "9zkjbpb475": ["Smith Machine Shoulder Press"],
  "a1lhyw9xlb": ["Smith Incline Shoulder Raise"],
  "a9hmu9r1js": ["Heavy Bag Thrust"],
  "anjay541ch": ["Smith Machine Bent Over Row"],
  "aw8r1j5s2w": ["Incline Curl (hantle)","Spider Curl","Incline Inner Biceps Curl"],
  "azjgylfxsc": ["Box Skip","Lateral Box Jump"],
  "b6strf67a8": ["Cable Lateral Raise","Cable Front Raise"],
  "b85xor1l3n": ["Single Arm Lat Pulldown"],
  "bbx3x1bzk2": ["Two-Arm Kettlebell Row"],
  "bgov5ybaah": ["Overhead Triceps Extension (EZ)"],
  "bj3bu7l1ae": ["Sandbag Load"],
  "bntayi602j": ["Smith Machine Bench Press"],
  "bqtd6rbe5n": ["Deadlift (hantle)"],
  "bqypobwepi": ["Nordic Curl"],
  "bwjddwef09": ["Kneeling Jump Squat"],
  "c04c69lz3h": ["Kettlebell Windmill"],
  "c087rkeq5e": ["Hip Abduction"],
  "c4ecq1j1qs": ["Single Leg Calf Raise"],
  "cd8kd47x6p": ["Band Squat"],
  "clm0fyembz": ["Cable Crunch"],
  "csyjsainvv": ["Band Hip Adductions"],
  "cu1ea9no40": ["Squeeze Press (hantle)"],
  "cz4t271qpi": ["Cable Lying Triceps Extension"],
  "d0zn91364c": ["Squat with Chains"],
  "d3vfc4s5sb": ["Leverage Shrug"],
  "d608tyn3ph": ["Log Lift"],
  "dfnir20lu4": ["Shrugs (hantle)"],
  "dhrsvhaju8": ["Ring Dips"],
  "doreic2y0u": ["Lying Face Down Plate Neck Resistance","Lying Face Up Plate Neck Resistance"],
  "dovf6zxa09": ["Two-Arm Kettlebell Military Press"],
  "doxu85jw8i": ["Cable Incline Pushdown"],
  "drifyoly58": ["Single-Arm Push-Up"],
  "e66mqjug4z": ["Handstand Push Up"],
  "e6ue4tlbu1": ["Meadows Row"],
  "e9yoc4t8gt": ["Seated One-Arm Dumbbell Palms-Up Wrist Curl","Seated One-Arm Dumbbell Palms-Down Wrist Curl"],
  "edtn44nac6": ["Skating"],
  "eewgmghpj5": ["Skakanka"],
  "egv2gzd8pg": ["Lying Close-Grip Bar Curl On High Pulley"],
  "ehhnki23uq": ["One-Arm Side Deadlift"],
  "ehndf1i6l7": ["Floor Press (hantle)"],
  "ej8uazshjn": ["Tire Flip"],
  "em7lsytjhf": ["Cable Judo Flip"],
  "f96vk18ns2": ["Power Jerk","Split Jerk","Squat Jerk"],
  "fc3vzyy5nj": ["Front Barbell Squat to a Bench"],
  "fd85wwd09h": ["Palms-Up Barbell Wrist Curl Over A Bench","Palms-Down Barbell Wrist Curl Over A Bench","Finger Curls"],
  "fdpceyyv88": ["Push Up to Side Plank"],
  "fi24rntp90": ["Standing Cable Leg Curl"],
  "fmq0ilsbgu": ["Downward Facing Balance"],
  "fmrq6n0ivu": ["Seated Flat Bench Leg Pull-In"],
  "fpb67b4moz": ["Snatch (hantel)"],
  "fq5dfdddyw": ["Single Arm Overhead Press (hantel)","Standing Palm-In One-Arm Dumbbell Press"],
  "fxpg79brry": ["Weighted Sissy Squat"],
  "g0ryv1zzol": ["Ski Erg"],
  "g4vf1g0txy": ["Bear Crawl Sled Drag"],
  "g7f0wq167i": ["Suitcase Carry"],
  "gaepa6ea06": ["Kettlebell Overhead Triceps Extension"],
  "ge47umoq8": ["Przysiad z pasem (linki)"],
  "gkf1v3ie2i": ["Frog Pump"],
  "gr7kohdmqn": ["Barbell Side Bend"],
  "gtfx0obck0": ["One Arm Pronated Dumbbell Triceps Extension","One Arm Supinated Dumbbell Triceps Extension"],
  "gxa60qfk6h": ["Single Leg RDL (hantel)"],
  "hbxffgfb6o": ["Svend Press"],
  "hc76547h1v": ["Smith Machine Decline Press"],
  "he3fp5m93s": ["Lying Leg Raise","Leg Pull-In","Oblique Crunches"],
  "hlqzwhhf15": ["Wide Stance Stiff-Legged Deadlift"],
  "hnvme7rwhp": ["One Arm Row (hantle)"],
  "hr7x03fiex": ["Barbell Rollout from Bench"],
  "hunb5x4kdk": ["Reverse Band Sumo Deadlift"],
  "i9fbrwu0": ["Stability Ball Crunch","Exercise Ball Pull-In"],
  "iem84nsimg": ["One-Arm Flat Bench Dumbbell Fly"],
  "ilx1exjj82": ["Reverse EZ-Bar Preacher Curl"],
  "ipich2aypd": ["Pistol Squat"],
  "j04n2e9kyh": ["Skullcrusher (sztanga)"],
  "j0btl40qo8": ["One-Arm Incline Lateral Raise"],
  "j141lky7g5": ["Rear Delt Raise (hantle)","Reverse Fly (hantle)"],
  "j3pp11gxso": ["Front Squat","Zercher Squat","Frankenstein Squat"],
  "j78d95bzv": ["Cable Kickback"],
  "jbrp3xnos8": ["Leverage Decline Chest Press"],
  "k5pmc7coza": ["Cable Woodchop"],
  "keaq9lr6dp": ["Cossack Squat"],
  "kfg9wveq8p": ["Kettlebell Thruster"],
  "kfo3rhpr1o": ["Cable Y Raise"],
  "kio5xriyhm": ["Preacher Hammer Dumbbell Curl"],
  "koexhd0fpl": ["Single-Leg High Box Squat"],
  "kqpvp64qfo": ["Cable Hip Adduction"],
  "kxpx5fkbps": ["Rope Straight-Arm Pulldown"],
  "l8l9tv88kz": ["Bottoms-Up Clean From The Hang Position"],
  "lqck9tfh3b": ["Barbell Shrug Behind The Back"],
  "lr5fiyqtuc": ["Step Up"],
  "ls6tg6796d": ["Linear 3-Part Start Technique","Moving Claw Series"],
  "lul2y5wl3c": ["Standing Gastrocnemius Calf Stretch"],
  "m0lkpq0l1n": ["Machine Crunch"],
  "m3sc8u62x0": ["Power Snatch"],
  "m8ngli93tp": ["Cable Rope Rear-Delt Rows"],
  "mdlm2npbvc": ["Gorilla Chin/Crunch"],
  "mpe78elob": ["Decline Bench Press","Wide-Grip Decline Barbell Bench Press"],
  "mvx7k9njuy": ["Single Leg Hip Thrust"],
  "myiz7bofsx": ["Dumbbell One-Arm Upright Row"],
  "n3kuwfcx5s": ["Standing Two-Arm Overhead Throw"],
  "n4c8m3pb24": ["Two-Arm Kettlebell Clean","Double Kettlebell Alternating Hang Clean"],
  "n6to7xfyw3": ["One-Arm High-Pulley Cable Side Bends"],
  "n89i8b42l3": ["Side to Side Box Shuffle"],
  "n9uqrg3c1y": ["Hip Lift with Band"],
  "nf9oljlq4o": ["Cable Wrist Curl"],
  "ntdaffvzif": ["Single-Leg Stride Jump"],
  "o07hnhyfcl": ["Physioball Hip Bridge"],
  "o28ueevgaj": ["Front Cone Hops"],
  "o4pu52e7ew": ["Lying Machine Squat"],
  "oefwoq1x6q": ["Incline Push-Up Close-Grip"],
  "ogu8oz11bi": ["Front Raise And Pullover"],
  "os9vdw7s78": ["Jefferson Squat"],
  "ou72lnby4n": ["Step-up with Knee Raise"],
  "oudsv2fda7": ["Single-Leg Leg Extension"],
  "ox55emu99b": ["Lunge Pass Through"],
  "ozw6z9okmk": ["Chest Supported Row"],
  "p6qpapm5a5": ["Good Morning off Pins"],
  "p7xcqmims5": ["Weighted Sit-Ups - With Bands"],
  "pcuf0c1ixf": ["Isometric Chest Squeezes"],
  "pf4n0s6f9r": ["Cable Incline Triceps Extension"],
  "q4hhwoncc6": ["Romanian Deadlift from Deficit"],
  "qiz9wx2w8": ["Decline Push Up"],
  "qjp3vu4blv": ["Crunch - Legs On Exercise Ball"],
  "qm4bactfgp": ["Bayesian Curl"],
  "qq1hh0pjit": ["Car Deadlift","Rickshaw Deadlift"],
  "qslgbnjc0n": ["Clean Shrug","Snatch Shrug"],
  "qu0otvbzjc": ["Lunges (hantle)"],
  "qwrlmmcd4i": ["Machine Triceps Extension"],
  "r0xdpzjkfi": ["Power Clean from Blocks"],
  "r2rzlq5bqe": ["Pin Press"],
  "r6hw1x0l7k": ["Diamond Push Up"],
  "rmegsqw92m": ["Decline Reverse Crunch"],
  "rmpet8lgm2": ["Łydki na stopniu"],
  "rqpld4b5jy": ["Seated Cable Chest Press"],
  "rs9n5bp32i": ["Medicine Ball Full Twist"],
  "s5rw18qrpr": ["Board Press","Reverse Triceps Bench Press"],
  "s88pq96m48": ["Calf Stretch Elbows Against Wall","Calf Stretch Hands Against Wall","Chair Leg Extended Stretch","Chair Lower Back Stretch","Chair Upper Body Stretch","Elbows Back","Middle Back Stretch","One Arm Against Wall","Overhead Stretch","Shoulder Stretch","Side Neck Stretch","Side Wrist Pull","Spinal Stretch","Standing Biceps Stretch","Standing Hip Flexors","Standing Lateral Stretch","Standing Soleus And Achilles Stretch","Standing Toe Touches","Tricep Side Stretch","Triceps Stretch","Upper Back Stretch"],
  "sb2wx1czqf": ["Machine Biceps Curl"],
  "sbuwbmp8ux": ["Isometric Neck Exercise - Front And Back","Isometric Neck Exercise - Sides"],
  "sg38lpn5i6": ["Incline Hammer Curl"],
  "shdi7rjds3": ["Walking Lunges","Reverse Lunge","Split Squat","Lateral Lunge"],
  "sk1q4gmhh0": ["T-Bar Row"],
  "sm4jatsz7": ["Bodyweight Squat"],
  "t0b4kgbdy1": ["Standing Olympic Plate Hand Squeeze"],
  "t4stvw7ups": ["Pallof Press"],
  "ta80lmy8ud": ["One-Arm Kettlebell Clean and Jerk"],
  "te3n0b13zn": ["Machine Lateral Raise"],
  "tf3g8fcywy": ["Standing Barbell Press Behind Neck"],
  "ti1zym5oh4": ["Bosu Ball Cable Crunch With Side Bends"],
  "tjhjuhrahf": ["Smith Machine Squat","Smith Machine Leg Press"],
  "tm85lujvwc": ["Standing Dumbbell Reverse Curl"],
  "tskx16vszb": ["One-Arm Open Palm Kettlebell Clean"],
  "twup2f4fwy": ["See-Saw Press (Alternating Side Press)"],
  "u1py2f92am": ["Dumbbell Clean"],
  "u86cpc9gtz": ["Cable Preacher Curl"],
  "udqvkijyro": ["Farmer's Walk (trap bar)"],
  "ug66cgk16i": ["Spider Crawl"],
  "ulaqywwrf1": ["Upright Row With Bands","Back Flyes - With Bands"],
  "uuj1pbmro5": ["GHD Sit Up"],
  "v0wcni6i0p": ["Reverse Hyperextension"],
  "v7ruvdmv02": ["Fire Hydrant","Clamshell"],
  "vb2g6zaebz": ["Y Raise (hantle)"],
  "vbuitjkuo6": ["Hanging Knee Raise"],
  "vdk9jmv38e": ["Torso Rotation"],
  "vhs44gizi": ["Rowing Machine"],
  "vigujk7v9f": ["Double Kettlebell Push Press","Double Kettlebell Jerk"],
  "vmwaa0ymxp": ["Seated Shoulder Press (hantle)"],
  "vmz4qcigzd": ["Hanging Alternating Knee Raise"],
  "vol2tefrv8": ["Barbell Seated Calf Raise"],
  "vvxo59mhc6": ["Depth Jump Leap","Linear Depth Jump"],
  "w08jbhsuok": ["Landmine Rotation"],
  "w16sh0kvgj": ["Leverage Incline Chest Press"],
  "w60umwent8": ["Cable Hip Abduction"],
  "w63z06lxue": ["Vertical Swing"],
  "wiqvpqbhcv": ["Sled Reverse Flye"],
  "x0qkay837z": ["Press Sit-Up"],
  "x47ow6yxk": ["Belt Squat Machine"],
  "xcq64rvqf5": ["Hanging Leg Raise"],
  "xkdtnhyqhu": ["Rocky Pull-Ups/Pulldowns","Wide-Grip Rear Pull-Up"],
  "xnqp5jepf7": ["Sled Overhead Triceps Extension"],
  "xubmiradkf": ["Dips - Triceps Version"],
  "y3164353sx": ["Kettlebell Press","Kettlebell Arnold Press","One-Arm Kettlebell Para Press"],
  "y67zwkhpyh": ["Single Leg Press"],
  "y8zfo2fh4h": ["Standing Calf Raise"],
  "yay706sw7z": ["Orbitrek"],
  "ypx9zsus1v": ["Bodyweight Mid Row"],
  "yrd7lqi8kc": ["Elevated Back Lunge"],
  "yw2l7wxbp1": ["Cable Seated Lateral Raise"],
  "z1n7fxt1b9": ["Chest Dip"],
  "z2swrr6ynb": ["Overhead Carry (hantle)"],
  "z3julvdbjh": ["One Arm Dumbbell Preacher Curl"],
  "zg3mx1037y": ["Speed Band Overhead Triceps"],
  "ziv3gtnbtg": ["Single Arm RDL (hantel/linka)"],
  "zjj2r5egll": ["Single Leg RDL (linki)"],
  "zmifg35ot0": ["Smith Machine One-Arm Upright Row"],
  "zqqadpv81x": ["Preacher Curl (EZ)","EZ-Bar Spider Curl"],
  "ztgcvmqdjw": ["Triceps Dips (ławka)"],
};
